# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'faraday/retry'
require 'sorbet-runtime'
require_relative 'sdk_hooks/hooks'
require_relative 'utils/retries'

module OpenApiSDK
  extend T::Sig

  class Polar
    extend T::Sig

    attr_accessor :organizations, :subscriptions, :oauth2_clients, :oauth2, :benefits, :products, :orders, :refunds, :checkouts, :files, :metrics, :license_keys, :checkout_links, :custom_fields, :discounts, :customers, :customer_portal_benefit_grants, :customer_portal_customers, :customer_portal_customer_meters, :customer_portal_downloadables, :customer_portal_license_keys, :customer_portal_orders, :customer_portal_organizations, :customer_portal_subscriptions, :customer_sessions, :events, :meters, :customer_meters

    sig do
      params(
        client: T.nilable(Faraday::Connection),
        retry_config: T.nilable(::OpenApiSDK::Utils::RetryConfig),
        timeout_ms: T.nilable(Integer),
        access_token: T.nilable(::String),
        security_source: T.nilable(T.proc.returns(Models::Shared::Security)),
        server: T.nilable(Symbol),
        server_url: T.nilable(String),
        url_params: T.nilable(T::Hash[Symbol, String])
      ).void
    end
    def initialize(client: nil, retry_config: nil, timeout_ms: nil, access_token: nil, security_source: nil, server: nil, server_url: nil, url_params: nil)
      ## Instantiates the SDK configuring it with the provided parameters.
      # @param [T.nilable(Faraday::Connection)] client The faraday HTTP client to use for all operations
      # @param [T.nilable(::OpenApiSDK::Utils::RetryConfig)] retry_config The retry configuration to use for all operations
      # @param [T.nilable(Integer)] timeout_ms Request timeout in milliseconds for all operations
      # @param [T.nilable(Models::Shared::Security)] security: The security details required for authentication
      # @param [T.proc.returns(T.nilable(Models::Shared::Security))] security_source: A function that returns security details required for authentication
      # @param [T.nilable(::Symbol)] server The server identifier to use for all operations
      # @param [T.nilable(::String)] server_url The server URL to use for all operations
      # @param [T.nilable(::Hash<::Symbol, ::String>)] url_params Parameters to optionally template the server URL with

      connection_options = {
        request: {
          params_encoder: Faraday::FlatParamsEncoder
        }
      }
      connection_options[:request][:timeout] = (timeout_ms.to_f / 1000) unless timeout_ms.nil?

      client ||= Faraday.new(**connection_options) do |f|
        f.request :multipart, {}
        # f.response :logger, nil, { headers: true, bodies: true, errors: true }
      end

      if !server_url.nil?
        if !url_params.nil?
          server_url = Utils.template_url(server_url, url_params)
        end
      end

      raise StandardError, "Invalid server \"#{server}\"" if !server.nil? && !SERVERS.key?(server)
      hooks = SDKHooks::Hooks.new
      @sdk_configuration = SDKConfiguration.new(
        client,
        hooks,
        retry_config,
        timeout_ms,
        access_token,
        security_source,
        server_url,
        server
      )

      original_server_url = @sdk_configuration.get_server_details.first
      new_server_url, @sdk_configuration.client = hooks.sdk_init(base_url: original_server_url, client: client)
      @sdk_configuration.server_url = new_server_url if new_server_url != original_server_url

      init_sdks
    end

    sig { void }
    def init_sdks
      @organizations = Organizations.new(@sdk_configuration)
      @subscriptions = Subscriptions.new(@sdk_configuration)
      @oauth2_clients = Oauth2Clients.new(@sdk_configuration)
      @oauth2 = Oauth2.new(@sdk_configuration)
      @benefits = Benefits.new(@sdk_configuration)
      @products = Products.new(@sdk_configuration)
      @orders = Orders.new(@sdk_configuration)
      @refunds = Refunds.new(@sdk_configuration)
      @checkouts = Checkouts.new(@sdk_configuration)
      @files = Files.new(@sdk_configuration)
      @metrics = Metrics.new(@sdk_configuration)
      @license_keys = LicenseKeys.new(@sdk_configuration)
      @checkout_links = CheckoutLinks.new(@sdk_configuration)
      @custom_fields = CustomFields.new(@sdk_configuration)
      @discounts = Discounts.new(@sdk_configuration)
      @customers = Customers.new(@sdk_configuration)
      @customer_portal_benefit_grants = CustomerPortalBenefitGrants.new(@sdk_configuration)
      @customer_portal_customers = CustomerPortalCustomers.new(@sdk_configuration)
      @customer_portal_customer_meters = CustomerPortalCustomerMeters.new(@sdk_configuration)
      @customer_portal_downloadables = CustomerPortalDownloadables.new(@sdk_configuration)
      @customer_portal_license_keys = CustomerPortalLicenseKeys.new(@sdk_configuration)
      @customer_portal_orders = CustomerPortalOrders.new(@sdk_configuration)
      @customer_portal_organizations = CustomerPortalOrganizations.new(@sdk_configuration)
      @customer_portal_subscriptions = CustomerPortalSubscriptions.new(@sdk_configuration)
      @customer_sessions = CustomerSessions.new(@sdk_configuration)
      @events = Events.new(@sdk_configuration)
      @meters = Meters.new(@sdk_configuration)
      @customer_meters = CustomerMeters.new(@sdk_configuration)
    end
  end
end
