# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema of a custom field attached to a resource.
      class AttachedCustomField
        extend T::Sig
        include Crystalline::MetadataFields


        field :custom_field, T.any(Models::Shared::CustomFieldText, Models::Shared::CustomFieldNumber, Models::Shared::CustomFieldDate, Models::Shared::CustomFieldCheckbox, Models::Shared::CustomFieldSelect), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('custom_field') }, 'discriminator': 'type' }
        # ID of the custom field.
        field :custom_field_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('custom_field_id') } }
        # Order of the custom field in the resource.
        field :order, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('order') } }
        # Whether the value is required for this custom field.
        field :required, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('required') } }


        sig { params(custom_field: T.any(Models::Shared::CustomFieldText, Models::Shared::CustomFieldNumber, Models::Shared::CustomFieldDate, Models::Shared::CustomFieldCheckbox, Models::Shared::CustomFieldSelect), custom_field_id: ::String, order: ::Integer, required: T::Boolean).void }
        def initialize(custom_field: nil, custom_field_id: nil, order: nil, required: nil)
          @custom_field = custom_field
          @custom_field_id = custom_field_id
          @order = order
          @required = required
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @custom_field == other.custom_field
          return false unless @custom_field_id == other.custom_field_id
          return false unless @order == other.order
          return false unless @required == other.required
          true
        end
      end
    end
  end
end
