# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class AuthorizationCodeTokenRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :client_id, ::String, { 'form': { 'field_name': 'client_id' } }

        field :client_secret, ::String, { 'form': { 'field_name': 'client_secret' } }

        field :code, ::String, { 'form': { 'field_name': 'code' } }

        field :grant_type, ::String, { 'form': { 'field_name': 'grant_type' } }

        field :redirect_uri, ::String, { 'form': { 'field_name': 'redirect_uri' } }


        sig { params(client_id: ::String, client_secret: ::String, code: ::String, grant_type: ::String, redirect_uri: ::String).void }
        def initialize(client_id: nil, client_secret: nil, code: nil, grant_type: nil, redirect_uri: nil)
          @client_id = client_id
          @client_secret = client_secret
          @code = code
          @grant_type = grant_type
          @redirect_uri = redirect_uri
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @client_id == other.client_id
          return false unless @client_secret == other.client_secret
          return false unless @code == other.code
          return false unless @grant_type == other.grant_type
          return false unless @redirect_uri == other.redirect_uri
          true
        end
      end
    end
  end
end
