# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class AuthorizeResponseUser
        extend T::Sig
        include Crystalline::MetadataFields


        field :client, Models::Shared::OAuth2ClientPublic, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client') } }

        field :scopes, T::Array[Models::Shared::Scope], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('scopes') } }

        field :sub, Models::Shared::AuthorizeUser, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sub') } }

        field :sub_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sub_type') } }


        sig { params(client: Models::Shared::OAuth2ClientPublic, scopes: T::Array[Models::Shared::Scope], sub: Models::Shared::AuthorizeUser, sub_type: ::String).void }
        def initialize(client: nil, scopes: nil, sub: nil, sub_type: nil)
          @client = client
          @scopes = scopes
          @sub = sub
          @sub_type = sub_type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @client == other.client
          return false unless @scopes == other.scopes
          return false unless @sub == other.sub
          return false unless @sub_type == other.sub_type
          true
        end
      end
    end
  end
end
