# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BenefitLicenseKeyExpirationProperties
        extend T::Sig
        include Crystalline::MetadataFields


        field :timeframe, Models::Shared::Timeframe, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('timeframe'), 'decoder': Utils.enum_from_string(Models::Shared::Timeframe, false) } }

        field :ttl, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ttl') } }


        sig { params(timeframe: Models::Shared::Timeframe, ttl: ::Integer).void }
        def initialize(timeframe: nil, ttl: nil)
          @timeframe = timeframe
          @ttl = ttl
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @timeframe == other.timeframe
          return false unless @ttl == other.ttl
          true
        end
      end
    end
  end
end
