# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BenefitSortProperty < T::Enum
        enums do
          CREATED_AT = new('created_at')
          MINUS_CREATED_AT = new('-created_at')
          DESCRIPTION = new('description')
          MINUS_DESCRIPTION = new('-description')
        end
      end
    end
  end
end
