# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BenefitGrantDownloadablesProperties
        extend T::Sig
        include Crystalline::MetadataFields


        field :files, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('files') } }


        sig { params(files: T.nilable(T::Array[::String])).void }
        def initialize(files: nil)
          @files = files
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @files == other.files
          true
        end
      end
    end
  end
end
