# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Properties available to subscribers for a benefit of type `discord`.
      class BenefitDiscordSubscriberProperties
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the Discord server.
        field :guild_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('guild_id') } }


        sig { params(guild_id: ::String).void }
        def initialize(guild_id: nil)
          @guild_id = guild_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @guild_id == other.guild_id
          true
        end
      end
    end
  end
end
