# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BenefitDownloadablesCreate
        extend T::Sig
        include Crystalline::MetadataFields

        # The description of the benefit. Will be displayed on products having this benefit.
        field :description, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }

        field :properties, Models::Shared::BenefitDownloadablesCreateProperties, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('properties') } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # The ID of the organization owning the benefit. **Required unless you use an organization token.**
        field :organization_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }


        sig { params(description: ::String, properties: Models::Shared::BenefitDownloadablesCreateProperties, type: ::String, metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), organization_id: T.nilable(::String)).void }
        def initialize(description: nil, properties: nil, type: nil, metadata: nil, organization_id: nil)
          @description = description
          @properties = properties
          @type = type
          @metadata = metadata
          @organization_id = organization_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @description == other.description
          return false unless @properties == other.properties
          return false unless @type == other.type
          return false unless @metadata == other.metadata
          return false unless @organization_id == other.organization_id
          true
        end
      end
    end
  end
end
