# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BenefitLicenseKeysProperties
        extend T::Sig
        include Crystalline::MetadataFields


        field :activations, Models::Shared::BenefitLicenseKeyActivationProperties, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('activations') } }

        field :expires, Models::Shared::BenefitLicenseKeyExpirationProperties, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('expires') } }

        field :limit_usage, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('limit_usage') } }

        field :prefix, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('prefix') } }


        sig { params(activations: Models::Shared::BenefitLicenseKeyActivationProperties, expires: Models::Shared::BenefitLicenseKeyExpirationProperties, limit_usage: ::Integer, prefix: ::String).void }
        def initialize(activations: nil, expires: nil, limit_usage: nil, prefix: nil)
          @activations = activations
          @expires = expires
          @limit_usage = limit_usage
          @prefix = prefix
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @activations == other.activations
          return false unless @expires == other.expires
          return false unless @limit_usage == other.limit_usage
          return false unless @prefix == other.prefix
          true
        end
      end
    end
  end
end
