# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BenefitGrantLicenseKeysProperties
        extend T::Sig
        include Crystalline::MetadataFields


        field :display_key, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('display_key') } }

        field :license_key_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('license_key_id') } }


        sig { params(display_key: T.nilable(::String), license_key_id: T.nilable(::String)).void }
        def initialize(display_key: nil, license_key_id: nil)
          @display_key = display_key
          @license_key_id = license_key_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @display_key == other.display_key
          return false unless @license_key_id == other.license_key_id
          true
        end
      end
    end
  end
end
