# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Properties for a benefit of type `custom`.
      class BenefitCustomProperties
        extend T::Sig
        include Crystalline::MetadataFields


        field :note, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('note') } }


        sig { params(note: ::String).void }
        def initialize(note: nil)
          @note = note
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @note == other.note
          true
        end
      end
    end
  end
end
