# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class BenefitDownloadablesProperties
        extend T::Sig
        include Crystalline::MetadataFields


        field :archived, T::Hash[Symbol, T::Boolean], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('archived') } }

        field :files, T::Array[::String], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('files') } }


        sig { params(archived: T::Hash[Symbol, T::Boolean], files: T::Array[::String]).void }
        def initialize(archived: nil, files: nil)
          @archived = archived
          @files = files
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @archived == other.archived
          return false unless @files == other.files
          true
        end
      end
    end
  end
end
