# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Product data for a checkout session.
      class CheckoutProduct
        extend T::Sig
        include Crystalline::MetadataFields

        # List of benefits granted by the product.
        field :benefits, T::Array[Models::Shared::BenefitPublic], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('benefits') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The description of the product.
        field :description, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }
        # The ID of the product.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Whether the product is archived and no longer available.
        field :is_archived, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('is_archived') } }
        # Whether the product is a subscription.
        field :is_recurring, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('is_recurring') } }
        # List of medias associated to the product.
        field :medias, T::Array[Models::Shared::ProductMediaFileRead], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('medias') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The name of the product.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # The ID of the organization owning the product.
        field :organization_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }
        # List of prices for this product.
        field :prices, T::Array[T.any(T.any(Models::Shared::LegacyRecurringProductPriceFixed, Models::Shared::LegacyRecurringProductPriceCustom, Models::Shared::LegacyRecurringProductPriceFree), T.any(Models::Shared::ProductPriceFixed, Models::Shared::ProductPriceCustom, Models::Shared::ProductPriceFree, Models::Shared::ProductPriceMeteredUnit))], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('prices') } }
        # The recurring interval of the product. If `None`, the product is a one-time purchase.
        field :recurring_interval, Models::Shared::SubscriptionRecurringInterval, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('recurring_interval'), 'decoder': Utils.enum_from_string(Models::Shared::SubscriptionRecurringInterval, false) } }


        sig { params(benefits: T::Array[Models::Shared::BenefitPublic], created_at: ::DateTime, description: ::String, id: ::String, is_archived: T::Boolean, is_recurring: T::Boolean, medias: T::Array[Models::Shared::ProductMediaFileRead], modified_at: ::DateTime, name: ::String, organization_id: ::String, prices: T::Array[T.any(T.any(Models::Shared::LegacyRecurringProductPriceFixed, Models::Shared::LegacyRecurringProductPriceCustom, Models::Shared::LegacyRecurringProductPriceFree), T.any(Models::Shared::ProductPriceFixed, Models::Shared::ProductPriceCustom, Models::Shared::ProductPriceFree, Models::Shared::ProductPriceMeteredUnit))], recurring_interval: Models::Shared::SubscriptionRecurringInterval).void }
        def initialize(benefits: nil, created_at: nil, description: nil, id: nil, is_archived: nil, is_recurring: nil, medias: nil, modified_at: nil, name: nil, organization_id: nil, prices: nil, recurring_interval: nil)
          @benefits = benefits
          @created_at = created_at
          @description = description
          @id = id
          @is_archived = is_archived
          @is_recurring = is_recurring
          @medias = medias
          @modified_at = modified_at
          @name = name
          @organization_id = organization_id
          @prices = prices
          @recurring_interval = recurring_interval
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefits == other.benefits
          return false unless @created_at == other.created_at
          return false unless @description == other.description
          return false unless @id == other.id
          return false unless @is_archived == other.is_archived
          return false unless @is_recurring == other.is_recurring
          return false unless @medias == other.medias
          return false unless @modified_at == other.modified_at
          return false unless @name == other.name
          return false unless @organization_id == other.organization_id
          return false unless @prices == other.prices
          return false unless @recurring_interval == other.recurring_interval
          true
        end
      end
    end
  end
end
