# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema for a percentage discount that is applied on every invoice
      # for a certain number of months.
      class CheckoutDiscountPercentageRepeatDuration
        extend T::Sig
        include Crystalline::MetadataFields


        field :basis_points, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('basis_points') } }

        field :code, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('code') } }

        field :duration, Models::Shared::DiscountDuration, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('duration'), 'decoder': Utils.enum_from_string(Models::Shared::DiscountDuration, false) } }

        field :duration_in_months, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('duration_in_months') } }
        # The ID of the object.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

        field :type, Models::Shared::DiscountType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), 'decoder': Utils.enum_from_string(Models::Shared::DiscountType, false) } }


        sig { params(basis_points: ::Integer, code: ::String, duration: Models::Shared::DiscountDuration, duration_in_months: ::Integer, id: ::String, name: ::String, type: Models::Shared::DiscountType).void }
        def initialize(basis_points: nil, code: nil, duration: nil, duration_in_months: nil, id: nil, name: nil, type: nil)
          @basis_points = basis_points
          @code = code
          @duration = duration
          @duration_in_months = duration_in_months
          @id = id
          @name = name
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @basis_points == other.basis_points
          return false unless @code == other.code
          return false unless @duration == other.duration
          return false unless @duration_in_months == other.duration_in_months
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
