# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Checkout link data.
      class CheckoutLink
        extend T::Sig
        include Crystalline::MetadataFields

        # Whether to allow the customer to apply discount codes. If you apply a discount through `discount_id`, it'll still be applied, but the customer won't be able to change it.
        field :allow_discount_codes, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('allow_discount_codes') } }
        # Client secret used to access the checkout link.
        field :client_secret, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client_secret') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :discount, T.any(Models::Shared::DiscountFixedOnceForeverDurationBase, Models::Shared::DiscountFixedRepeatDurationBase, Models::Shared::DiscountPercentageOnceForeverDurationBase, Models::Shared::DiscountPercentageRepeatDurationBase), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount') } }
        # ID of the discount to apply to the checkout. If the discount is not applicable anymore when opening the checkout link, it'll be ignored.
        field :discount_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount_id') } }
        # The ID of the object.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Optional label to distinguish links internally
        field :label, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('label') } }

        field :metadata, T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The organization ID.
        field :organization_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

        field :payment_processor, Models::Shared::PaymentProcessor, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('payment_processor'), 'decoder': Utils.enum_from_string(Models::Shared::PaymentProcessor, false) } }

        field :products, T::Array[Models::Shared::CheckoutLinkProduct], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('products') } }
        # Whether to require the customer to fill their full billing address, instead of just the country. Customers in the US will always be required to fill their full address, regardless of this setting.
        field :require_billing_address, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('require_billing_address') } }
        # URL where the customer will be redirected after a successful payment.
        field :success_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('success_url') } }

        field :url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('url') } }


        sig { params(allow_discount_codes: T::Boolean, client_secret: ::String, created_at: ::DateTime, discount: T.any(Models::Shared::DiscountFixedOnceForeverDurationBase, Models::Shared::DiscountFixedRepeatDurationBase, Models::Shared::DiscountPercentageOnceForeverDurationBase, Models::Shared::DiscountPercentageRepeatDurationBase), discount_id: ::String, id: ::String, label: ::String, metadata: T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], modified_at: ::DateTime, organization_id: ::String, payment_processor: Models::Shared::PaymentProcessor, products: T::Array[Models::Shared::CheckoutLinkProduct], require_billing_address: T::Boolean, success_url: ::String, url: ::String).void }
        def initialize(allow_discount_codes: nil, client_secret: nil, created_at: nil, discount: nil, discount_id: nil, id: nil, label: nil, metadata: nil, modified_at: nil, organization_id: nil, payment_processor: nil, products: nil, require_billing_address: nil, success_url: nil, url: nil)
          @allow_discount_codes = allow_discount_codes
          @client_secret = client_secret
          @created_at = created_at
          @discount = discount
          @discount_id = discount_id
          @id = id
          @label = label
          @metadata = metadata
          @modified_at = modified_at
          @organization_id = organization_id
          @payment_processor = payment_processor
          @products = products
          @require_billing_address = require_billing_address
          @success_url = success_url
          @url = url
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @allow_discount_codes == other.allow_discount_codes
          return false unless @client_secret == other.client_secret
          return false unless @created_at == other.created_at
          return false unless @discount == other.discount
          return false unless @discount_id == other.discount_id
          return false unless @id == other.id
          return false unless @label == other.label
          return false unless @metadata == other.metadata
          return false unless @modified_at == other.modified_at
          return false unless @organization_id == other.organization_id
          return false unless @payment_processor == other.payment_processor
          return false unless @products == other.products
          return false unless @require_billing_address == other.require_billing_address
          return false unless @success_url == other.success_url
          return false unless @url == other.url
          true
        end
      end
    end
  end
end
