# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerCreate
        extend T::Sig
        include Crystalline::MetadataFields

        # The email address of the customer. This must be unique within the organization.
        field :email, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }

        field :billing_address, T.nilable(Models::Shared::Address), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('billing_address') } }
        # The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
        field :external_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_id') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # The name of the customer.
        field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # The ID of the organization owning the customer. **Required unless you use an organization token.**
        field :organization_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

        field :tax_id, T.nilable(T::Array[T.any(::String, Models::Shared::TaxIDFormat)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tax_id') } }


        sig { params(email: ::String, billing_address: T.nilable(Models::Shared::Address), external_id: T.nilable(::String), metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), name: T.nilable(::String), organization_id: T.nilable(::String), tax_id: T.nilable(T::Array[T.any(::String, Models::Shared::TaxIDFormat)])).void }
        def initialize(email: nil, billing_address: nil, external_id: nil, metadata: nil, name: nil, organization_id: nil, tax_id: nil)
          @email = email
          @billing_address = billing_address
          @external_id = external_id
          @metadata = metadata
          @name = name
          @organization_id = organization_id
          @tax_id = tax_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @email == other.email
          return false unless @billing_address == other.billing_address
          return false unless @external_id == other.external_id
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          return false unless @organization_id == other.organization_id
          return false unless @tax_id == other.tax_id
          true
        end
      end
    end
  end
end
