# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerPortalOAuthAccount
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('account_id') } }

        field :account_username, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('account_username') } }


        sig { params(account_id: ::String, account_username: ::String).void }
        def initialize(account_id: nil, account_username: nil)
          @account_id = account_id
          @account_username = account_username
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @account_username == other.account_username
          true
        end
      end
    end
  end
end
