# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema to update a custom field of type number.
      class CustomFieldUpdateNumber
        extend T::Sig
        include Crystalline::MetadataFields


        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }

        field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

        field :properties, T.nilable(Models::Shared::CustomFieldNumberProperties), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('properties') } }

        field :slug, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('slug') } }


        sig { params(type: ::String, metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), name: T.nilable(::String), properties: T.nilable(Models::Shared::CustomFieldNumberProperties), slug: T.nilable(::String)).void }
        def initialize(type: nil, metadata: nil, name: nil, properties: nil, slug: nil)
          @type = type
          @metadata = metadata
          @name = name
          @properties = properties
          @slug = slug
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          return false unless @properties == other.properties
          return false unless @slug == other.slug
          true
        end
      end
    end
  end
end
