# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # An active meter for a customer, with latest consumed and credited units.
      class CustomerStateMeter
        extend T::Sig
        include Crystalline::MetadataFields

        # The balance of the meter, i.e. the difference between credited and consumed units. Never goes negative.
        field :balance, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('balance') } }
        # The number of consumed units.
        field :consumed_units, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('consumed_units') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The number of credited units.
        field :credited_units, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('credited_units') } }
        # The ID of the meter.
        field :meter_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('meter_id') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }


        sig { params(balance: ::Float, consumed_units: ::Float, created_at: ::DateTime, credited_units: ::Integer, meter_id: ::String, modified_at: ::DateTime).void }
        def initialize(balance: nil, consumed_units: nil, created_at: nil, credited_units: nil, meter_id: nil, modified_at: nil)
          @balance = balance
          @consumed_units = consumed_units
          @created_at = created_at
          @credited_units = credited_units
          @meter_id = meter_id
          @modified_at = modified_at
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @balance == other.balance
          return false unless @consumed_units == other.consumed_units
          return false unless @created_at == other.created_at
          return false unless @credited_units == other.credited_units
          return false unless @meter_id == other.meter_id
          return false unless @modified_at == other.modified_at
          true
        end
      end
    end
  end
end
