# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema of an organization and related data for customer portal.
      class CustomerOrganization
        extend T::Sig
        include Crystalline::MetadataFields


        field :organization, Models::Shared::Organization, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization') } }

        field :products, T::Array[Models::Shared::CustomerProduct], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('products') } }


        sig { params(organization: Models::Shared::Organization, products: T::Array[Models::Shared::CustomerProduct]).void }
        def initialize(organization: nil, products: nil)
          @organization = organization
          @products = products
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @organization == other.organization
          return false unless @products == other.products
          true
        end
      end
    end
  end
end
