# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerSubscriptionUpdateProduct
        extend T::Sig
        include Crystalline::MetadataFields

        # Update subscription to another product.
        field :product_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_id') } }


        sig { params(product_id: ::String).void }
        def initialize(product_id: nil)
          @product_id = product_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @product_id == other.product_id
          true
        end
      end
    end
  end
end
