# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema to create a custom field of type checkbox.
      class CustomFieldCreateCheckbox
        extend T::Sig
        include Crystalline::MetadataFields

        # Name of the custom field.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

        field :properties, Models::Shared::CustomFieldCheckboxProperties, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('properties') } }
        # Identifier of the custom field. It'll be used as key when storing the value. Must be unique across the organization.It can only contain ASCII letters, numbers and hyphens.
        field :slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('slug') } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # The ID of the organization owning the custom field. **Required unless you use an organization token.**
        field :organization_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }


        sig { params(name: ::String, properties: Models::Shared::CustomFieldCheckboxProperties, slug: ::String, type: ::String, metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), organization_id: T.nilable(::String)).void }
        def initialize(name: nil, properties: nil, slug: nil, type: nil, metadata: nil, organization_id: nil)
          @name = name
          @properties = properties
          @slug = slug
          @type = type
          @metadata = metadata
          @organization_id = organization_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @properties == other.properties
          return false unless @slug == other.slug
          return false unless @type == other.type
          return false unless @metadata == other.metadata
          return false unless @organization_id == other.organization_id
          true
        end
      end
    end
  end
end
