# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerBenefitGrantLicenseKeysUpdate
        extend T::Sig
        include Crystalline::MetadataFields


        field :benefit_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('benefit_type') } }


        sig { params(benefit_type: ::String).void }
        def initialize(benefit_type: nil)
          @benefit_type = benefit_type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefit_type == other.benefit_type
          true
        end
      end
    end
  end
end
