# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # A customer session that can be used to authenticate as a customer.
      class CustomerSession
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # A customer in an organization.
        field :customer, Models::Shared::Customer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer') } }

        field :customer_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_id') } }

        field :customer_portal_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_portal_url') } }

        field :expires_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('expires_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The ID of the object.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :token, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('token') } }


        sig { params(created_at: ::DateTime, customer: Models::Shared::Customer, customer_id: ::String, customer_portal_url: ::String, expires_at: ::DateTime, id: ::String, modified_at: ::DateTime, token: ::String).void }
        def initialize(created_at: nil, customer: nil, customer_id: nil, customer_portal_url: nil, expires_at: nil, id: nil, modified_at: nil, token: nil)
          @created_at = created_at
          @customer = customer
          @customer_id = customer_id
          @customer_portal_url = customer_portal_url
          @expires_at = expires_at
          @id = id
          @modified_at = modified_at
          @token = token
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @created_at == other.created_at
          return false unless @customer == other.customer
          return false unless @customer_id == other.customer_id
          return false unless @customer_portal_url == other.customer_portal_url
          return false unless @expires_at == other.expires_at
          return false unless @id == other.id
          return false unless @modified_at == other.modified_at
          return false unless @token == other.token
          true
        end
      end
    end
  end
end
