# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomFieldType < T::Enum
        enums do
          TEXT = new('text')
          NUMBER = new('number')
          DATE = new('date')
          CHECKBOX = new('checkbox')
          SELECT = new('select')
        end
      end
    end
  end
end
