# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerPortalCustomerUpdate
        extend T::Sig
        include Crystalline::MetadataFields


        field :billing_address, T.nilable(Models::Shared::Address), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('billing_address') } }

        field :email, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }

        field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

        field :tax_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tax_id') } }


        sig { params(billing_address: T.nilable(Models::Shared::Address), email: T.nilable(::String), name: T.nilable(::String), tax_id: T.nilable(::String)).void }
        def initialize(billing_address: nil, email: nil, name: nil, tax_id: nil)
          @billing_address = billing_address
          @email = email
          @name = name
          @tax_id = tax_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @billing_address == other.billing_address
          return false unless @email == other.email
          return false unless @name == other.name
          return false unless @tax_id == other.tax_id
          true
        end
      end
    end
  end
end
