# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerMeterSortProperty < T::Enum
        enums do
          CREATED_AT = new('created_at')
          MINUS_CREATED_AT = new('-created_at')
          MODIFIED_AT = new('modified_at')
          MINUS_MODIFIED_AT = new('-modified_at')
          CUSTOMER_ID = new('customer_id')
          MINUS_CUSTOMER_ID = new('-customer_id')
          CUSTOMER_NAME = new('customer_name')
          MINUS_CUSTOMER_NAME = new('-customer_name')
          METER_ID = new('meter_id')
          MINUS_METER_ID = new('-meter_id')
          METER_NAME = new('meter_name')
          MINUS_METER_NAME = new('-meter_name')
          CONSUMED_UNITS = new('consumed_units')
          MINUS_CONSUMED_UNITS = new('-consumed_units')
          CREDITED_UNITS = new('credited_units')
          MINUS_CREDITED_UNITS = new('-credited_units')
          BALANCE = new('balance')
          MINUS_BALANCE = new('-balance')
        end
      end
    end
  end
end
