# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerOrderSubscription
        extend T::Sig
        include Crystalline::MetadataFields

        # The amount of the subscription.
        field :amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount') } }
        # Whether the subscription will be canceled at the end of the current period.
        field :cancel_at_period_end, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cancel_at_period_end') } }
        # The timestamp when the subscription was canceled. The subscription might still be active if `cancel_at_period_end` is `true`.
        field :canceled_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('canceled_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :checkout_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('checkout_id') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The currency of the subscription.
        field :currency, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('currency') } }
        # The end timestamp of the current billing period.
        field :current_period_end, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('current_period_end'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The start timestamp of the current billing period.
        field :current_period_start, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('current_period_start'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :customer_cancellation_comment, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_cancellation_comment') } }

        field :customer_cancellation_reason, Models::Shared::CustomerCancellationReason, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_cancellation_reason'), 'decoder': Utils.enum_from_string(Models::Shared::CustomerCancellationReason, false) } }
        # The ID of the subscribed customer.
        field :customer_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_id') } }
        # The ID of the applied discount, if any.
        field :discount_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount_id') } }
        # The timestamp when the subscription ended.
        field :ended_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ended_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The timestamp when the subscription will end.
        field :ends_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ends_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The ID of the object.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The ID of the subscribed product.
        field :product_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_id') } }

        field :recurring_interval, Models::Shared::SubscriptionRecurringInterval, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('recurring_interval'), 'decoder': Utils.enum_from_string(Models::Shared::SubscriptionRecurringInterval, false) } }
        # The timestamp when the subscription started.
        field :started_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('started_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :status, Models::Shared::SubscriptionStatus, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Shared::SubscriptionStatus, false) } }


        sig { params(amount: ::Integer, cancel_at_period_end: T::Boolean, canceled_at: ::DateTime, checkout_id: ::String, created_at: ::DateTime, currency: ::String, current_period_end: ::DateTime, current_period_start: ::DateTime, customer_cancellation_comment: ::String, customer_cancellation_reason: Models::Shared::CustomerCancellationReason, customer_id: ::String, discount_id: ::String, ended_at: ::DateTime, ends_at: ::DateTime, id: ::String, modified_at: ::DateTime, product_id: ::String, recurring_interval: Models::Shared::SubscriptionRecurringInterval, started_at: ::DateTime, status: Models::Shared::SubscriptionStatus).void }
        def initialize(amount: nil, cancel_at_period_end: nil, canceled_at: nil, checkout_id: nil, created_at: nil, currency: nil, current_period_end: nil, current_period_start: nil, customer_cancellation_comment: nil, customer_cancellation_reason: nil, customer_id: nil, discount_id: nil, ended_at: nil, ends_at: nil, id: nil, modified_at: nil, product_id: nil, recurring_interval: nil, started_at: nil, status: nil)
          @amount = amount
          @cancel_at_period_end = cancel_at_period_end
          @canceled_at = canceled_at
          @checkout_id = checkout_id
          @created_at = created_at
          @currency = currency
          @current_period_end = current_period_end
          @current_period_start = current_period_start
          @customer_cancellation_comment = customer_cancellation_comment
          @customer_cancellation_reason = customer_cancellation_reason
          @customer_id = customer_id
          @discount_id = discount_id
          @ended_at = ended_at
          @ends_at = ends_at
          @id = id
          @modified_at = modified_at
          @product_id = product_id
          @recurring_interval = recurring_interval
          @started_at = started_at
          @status = status
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @cancel_at_period_end == other.cancel_at_period_end
          return false unless @canceled_at == other.canceled_at
          return false unless @checkout_id == other.checkout_id
          return false unless @created_at == other.created_at
          return false unless @currency == other.currency
          return false unless @current_period_end == other.current_period_end
          return false unless @current_period_start == other.current_period_start
          return false unless @customer_cancellation_comment == other.customer_cancellation_comment
          return false unless @customer_cancellation_reason == other.customer_cancellation_reason
          return false unless @customer_id == other.customer_id
          return false unless @discount_id == other.discount_id
          return false unless @ended_at == other.ended_at
          return false unless @ends_at == other.ends_at
          return false unless @id == other.id
          return false unless @modified_at == other.modified_at
          return false unless @product_id == other.product_id
          return false unless @recurring_interval == other.recurring_interval
          return false unless @started_at == other.started_at
          return false unless @status == other.status
          true
        end
      end
    end
  end
end
