# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomFieldSelectProperties
        extend T::Sig
        include Crystalline::MetadataFields


        field :options, T::Array[Models::Shared::CustomFieldSelectOption], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('options') } }

        field :form_help_text, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('form_help_text') } }

        field :form_label, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('form_label') } }

        field :form_placeholder, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('form_placeholder') } }


        sig { params(options: T::Array[Models::Shared::CustomFieldSelectOption], form_help_text: T.nilable(::String), form_label: T.nilable(::String), form_placeholder: T.nilable(::String)).void }
        def initialize(options: nil, form_help_text: nil, form_label: nil, form_placeholder: nil)
          @options = options
          @form_help_text = form_help_text
          @form_label = form_label
          @form_placeholder = form_placeholder
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @options == other.options
          return false unless @form_help_text == other.form_help_text
          return false unless @form_label == other.form_label
          return false unless @form_placeholder == other.form_placeholder
          true
        end
      end
    end
  end
end
