# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema for creating a customer session using an external customer ID.
      class CustomerSessionCustomerExternalIDCreate
        extend T::Sig
        include Crystalline::MetadataFields

        # External ID of the customer to create a session for.
        field :customer_external_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_external_id') } }


        sig { params(customer_external_id: ::String).void }
        def initialize(customer_external_id: nil)
          @customer_external_id = customer_external_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @customer_external_id == other.customer_external_id
          true
        end
      end
    end
  end
end
