# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerCancellationReason < T::Enum
        enums do
          CUSTOMER_SERVICE = new('customer_service')
          LOW_QUALITY = new('low_quality')
          MISSING_FEATURES = new('missing_features')
          SWITCHED_SERVICE = new('switched_service')
          TOO_COMPLEX = new('too_complex')
          TOO_EXPENSIVE = new('too_expensive')
          UNUSED = new('unused')
          OTHER = new('other')
        end
      end
    end
  end
end
