# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerBenefitGrantGitHubRepositoryUpdate
        extend T::Sig
        include Crystalline::MetadataFields


        field :benefit_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('benefit_type') } }

        field :properties, Models::Shared::CustomerBenefitGrantGitHubRepositoryPropertiesUpdate, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('properties') } }


        sig { params(benefit_type: ::String, properties: Models::Shared::CustomerBenefitGrantGitHubRepositoryPropertiesUpdate).void }
        def initialize(benefit_type: nil, properties: nil)
          @benefit_type = benefit_type
          @properties = properties
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefit_type == other.benefit_type
          return false unless @properties == other.properties
          true
        end
      end
    end
  end
end
