# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerSubscriptionCancel
        extend T::Sig
        include Crystalline::MetadataFields

        # Cancel an active subscription once the current period ends.
        # 
        # Or uncancel a subscription currently set to be revoked at period end.
        field :cancel_at_period_end, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cancel_at_period_end') } }
        # Customer feedback and why they decided to cancel.
        field :cancellation_comment, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cancellation_comment') } }
        # Customers reason for cancellation.
        # 
        # * `too_expensive`: Too expensive for the customer.
        # * `missing_features`: Customer is missing certain features.
        # * `switched_service`: Customer switched to another service.
        # * `unused`: Customer is not using it enough.
        # * `customer_service`: Customer is not satisfied with the customer service.
        # * `low_quality`: Customer is unhappy with the quality.
        # * `too_complex`: Customer considers the service too complicated.
        # * `other`: Other reason(s).
        field :cancellation_reason, T.nilable(Models::Shared::CustomerCancellationReason), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cancellation_reason'), 'decoder': Utils.enum_from_string(Models::Shared::CustomerCancellationReason, true) } }


        sig { params(cancel_at_period_end: T.nilable(T::Boolean), cancellation_comment: T.nilable(::String), cancellation_reason: T.nilable(Models::Shared::CustomerCancellationReason)).void }
        def initialize(cancel_at_period_end: nil, cancellation_comment: nil, cancellation_reason: nil)
          @cancel_at_period_end = cancel_at_period_end
          @cancellation_comment = cancellation_comment
          @cancellation_reason = cancellation_reason
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @cancel_at_period_end == other.cancel_at_period_end
          return false unless @cancellation_comment == other.cancellation_comment
          return false unless @cancellation_reason == other.cancellation_reason
          true
        end
      end
    end
  end
end
