# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class CustomerCustomerMeterMeter
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The ID of the object.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The name of the meter. Will be shown on customer's invoices and usage.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }


        sig { params(created_at: ::DateTime, id: ::String, modified_at: ::DateTime, name: ::String).void }
        def initialize(created_at: nil, id: nil, modified_at: nil, name: nil)
          @created_at = created_at
          @id = id
          @modified_at = modified_at
          @name = name
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @modified_at == other.modified_at
          return false unless @name == other.name
          true
        end
      end
    end
  end
end
