# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema to create a fixed amount discount that is applied once or forever.
      class DiscountFixedOnceForeverDurationCreate
        extend T::Sig
        include Crystalline::MetadataFields

        # Fixed amount to discount from the invoice total.
        field :amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount') } }

        field :duration, Models::Shared::DiscountDuration, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('duration'), 'decoder': Utils.enum_from_string(Models::Shared::DiscountDuration, false) } }
        # Name of the discount. Will be displayed to the customer when the discount is applied.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

        field :type, Models::Shared::DiscountType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), 'decoder': Utils.enum_from_string(Models::Shared::DiscountType, false) } }
        # Code customers can use to apply the discount during checkout. Must be between 3 and 256 characters long and contain only alphanumeric characters.If not provided, the discount can only be applied via the API.
        field :code, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('code') } }
        # The currency. Currently, only `usd` is supported.
        field :currency, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('currency') } }
        # Optional timestamp after which the discount is no longer redeemable.
        field :ends_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ends_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # Optional maximum number of times the discount can be redeemed.
        field :max_redemptions, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_redemptions') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # The ID of the organization owning the discount. **Required unless you use an organization token.**
        field :organization_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

        field :products, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('products') } }
        # Optional timestamp after which the discount is redeemable.
        field :starts_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('starts_at'), 'decoder': Utils.datetime_from_iso_format(true) } }


        sig { params(amount: ::Integer, duration: Models::Shared::DiscountDuration, name: ::String, type: Models::Shared::DiscountType, code: T.nilable(::String), currency: T.nilable(::String), ends_at: T.nilable(::DateTime), max_redemptions: T.nilable(::Integer), metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), organization_id: T.nilable(::String), products: T.nilable(T::Array[::String]), starts_at: T.nilable(::DateTime)).void }
        def initialize(amount: nil, duration: nil, name: nil, type: nil, code: nil, currency: nil, ends_at: nil, max_redemptions: nil, metadata: nil, organization_id: nil, products: nil, starts_at: nil)
          @amount = amount
          @duration = duration
          @name = name
          @type = type
          @code = code
          @currency = currency
          @ends_at = ends_at
          @max_redemptions = max_redemptions
          @metadata = metadata
          @organization_id = organization_id
          @products = products
          @starts_at = starts_at
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @duration == other.duration
          return false unless @name == other.name
          return false unless @type == other.type
          return false unless @code == other.code
          return false unless @currency == other.currency
          return false unless @ends_at == other.ends_at
          return false unless @max_redemptions == other.max_redemptions
          return false unless @metadata == other.metadata
          return false unless @organization_id == other.organization_id
          return false unless @products == other.products
          return false unless @starts_at == other.starts_at
          true
        end
      end
    end
  end
end
