# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class DiscountSortProperty < T::Enum
        enums do
          CREATED_AT = new('created_at')
          MINUS_CREATED_AT = new('-created_at')
          NAME = new('name')
          MINUS_NAME = new('-name')
          CODE = new('code')
          MINUS_CODE = new('-code')
          REDEMPTIONS_COUNT = new('redemptions_count')
          MINUS_REDEMPTIONS_COUNT = new('-redemptions_count')
        end
      end
    end
  end
end
