# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema to update a discount.
      class DiscountUpdate
        extend T::Sig
        include Crystalline::MetadataFields


        field :amount, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount') } }

        field :basis_points, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('basis_points') } }

        field :code, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('code') } }

        field :currency, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('currency') } }

        field :duration, T.nilable(Models::Shared::DiscountDuration), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('duration'), 'decoder': Utils.enum_from_string(Models::Shared::DiscountDuration, true) } }

        field :duration_in_months, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('duration_in_months') } }

        field :ends_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ends_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :max_redemptions, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_redemptions') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }

        field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

        field :products, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('products') } }

        field :starts_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('starts_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :type, T.nilable(Models::Shared::DiscountType), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), 'decoder': Utils.enum_from_string(Models::Shared::DiscountType, true) } }


        sig { params(amount: T.nilable(::Integer), basis_points: T.nilable(::Integer), code: T.nilable(::String), currency: T.nilable(::String), duration: T.nilable(Models::Shared::DiscountDuration), duration_in_months: T.nilable(::Integer), ends_at: T.nilable(::DateTime), max_redemptions: T.nilable(::Integer), metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), name: T.nilable(::String), products: T.nilable(T::Array[::String]), starts_at: T.nilable(::DateTime), type: T.nilable(Models::Shared::DiscountType)).void }
        def initialize(amount: nil, basis_points: nil, code: nil, currency: nil, duration: nil, duration_in_months: nil, ends_at: nil, max_redemptions: nil, metadata: nil, name: nil, products: nil, starts_at: nil, type: nil)
          @amount = amount
          @basis_points = basis_points
          @code = code
          @currency = currency
          @duration = duration
          @duration_in_months = duration_in_months
          @ends_at = ends_at
          @max_redemptions = max_redemptions
          @metadata = metadata
          @name = name
          @products = products
          @starts_at = starts_at
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @basis_points == other.basis_points
          return false unless @code == other.code
          return false unless @currency == other.currency
          return false unless @duration == other.duration
          return false unless @duration_in_months == other.duration_in_months
          return false unless @ends_at == other.ends_at
          return false unless @max_redemptions == other.max_redemptions
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          return false unless @products == other.products
          return false unless @starts_at == other.starts_at
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
