# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Event
        extend T::Sig
        include Crystalline::MetadataFields

        # The customer associated with the event.
        field :customer, Models::Shared::Customer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer') } }
        # ID of the customer in your Polar organization associated with the event.
        field :customer_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_id') } }
        # ID of the customer in your system associated with the event.
        field :external_customer_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_customer_id') } }
        # The ID of the object.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

        field :metadata, T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # The name of the event.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # The ID of the organization owning the event.
        field :organization_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

        field :source, Models::Shared::EventSource, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('source'), 'decoder': Utils.enum_from_string(Models::Shared::EventSource, false) } }
        # The timestamp of the event.
        field :timestamp, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('timestamp'), 'decoder': Utils.datetime_from_iso_format(false) } }


        sig { params(customer: Models::Shared::Customer, customer_id: ::String, external_customer_id: ::String, id: ::String, metadata: T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], name: ::String, organization_id: ::String, source: Models::Shared::EventSource, timestamp: ::DateTime).void }
        def initialize(customer: nil, customer_id: nil, external_customer_id: nil, id: nil, metadata: nil, name: nil, organization_id: nil, source: nil, timestamp: nil)
          @customer = customer
          @customer_id = customer_id
          @external_customer_id = external_customer_id
          @id = id
          @metadata = metadata
          @name = name
          @organization_id = organization_id
          @source = source
          @timestamp = timestamp
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @customer == other.customer
          return false unless @customer_id == other.customer_id
          return false unless @external_customer_id == other.external_customer_id
          return false unless @id == other.id
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          return false unless @organization_id == other.organization_id
          return false unless @source == other.source
          return false unless @timestamp == other.timestamp
          true
        end
      end
    end
  end
end
