# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class EventsIngest
        extend T::Sig
        include Crystalline::MetadataFields

        # List of events to ingest.
        field :events, T::Array[T.any(Models::Shared::EventCreateCustomer, Models::Shared::EventCreateExternalCustomer)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('events') } }


        sig { params(events: T::Array[T.any(Models::Shared::EventCreateCustomer, Models::Shared::EventCreateExternalCustomer)]).void }
        def initialize(events: nil)
          @events = events
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @events == other.events
          true
        end
      end
    end
  end
end
