# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class EventSortProperty < T::Enum
        enums do
          TIMESTAMP = new('timestamp')
          MINUS_TIMESTAMP = new('-timestamp')
        end
      end
    end
  end
end
