# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class EventSource < T::Enum
        enums do
          SYSTEM = new('system')
          USER = new('user')
        end
      end
    end
  end
end
