# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class EventsIngestResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # Number of events inserted.
        field :inserted, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('inserted') } }


        sig { params(inserted: ::Integer).void }
        def initialize(inserted: nil)
          @inserted = inserted
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @inserted == other.inserted
          true
        end
      end
    end
  end
end
