# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Func < T::Enum
        enums do
          SUM = new('sum')
          MAX = new('max')
          MIN = new('min')
          AVG = new('avg')
        end
      end
    end
  end
end
