# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class IntrospectTokenRequestTokenTypeHint < T::Enum
        enums do
          ACCESS_TOKEN = new('access_token')
          REFRESH_TOKEN = new('refresh_token')
        end
      end
    end
  end
end
