# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # A recurring price for a product, i.e. a subscription.
      # 
      # **Deprecated**: The recurring interval should be set on the product itself.
      class LegacyRecurringProductPriceFixed
        extend T::Sig
        include Crystalline::MetadataFields


        field :amount_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount_type') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The ID of the price.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Whether the price is archived and no longer available.
        field :is_archived, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('is_archived') } }

        field :legacy, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('legacy') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The price in cents.
        field :price_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('price_amount') } }
        # The currency.
        field :price_currency, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('price_currency') } }
        # The ID of the product owning the price.
        field :product_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_id') } }

        field :recurring_interval, Models::Shared::SubscriptionRecurringInterval, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('recurring_interval'), 'decoder': Utils.enum_from_string(Models::Shared::SubscriptionRecurringInterval, false) } }
        # The type of the price.
        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


        sig { params(amount_type: ::String, created_at: ::DateTime, id: ::String, is_archived: T::Boolean, legacy: T::Boolean, modified_at: ::DateTime, price_amount: ::Integer, price_currency: ::String, product_id: ::String, recurring_interval: Models::Shared::SubscriptionRecurringInterval, type: ::String).void }
        def initialize(amount_type: nil, created_at: nil, id: nil, is_archived: nil, legacy: nil, modified_at: nil, price_amount: nil, price_currency: nil, product_id: nil, recurring_interval: nil, type: nil)
          @amount_type = amount_type
          @created_at = created_at
          @id = id
          @is_archived = is_archived
          @legacy = legacy
          @modified_at = modified_at
          @price_amount = price_amount
          @price_currency = price_currency
          @product_id = product_id
          @recurring_interval = recurring_interval
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount_type == other.amount_type
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @is_archived == other.is_archived
          return false unless @legacy == other.legacy
          return false unless @modified_at == other.modified_at
          return false unless @price_amount == other.price_amount
          return false unless @price_currency == other.price_currency
          return false unless @product_id == other.product_id
          return false unless @recurring_interval == other.recurring_interval
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
