# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class LicenseKeyCustomer
        extend T::Sig
        include Crystalline::MetadataFields


        field :avatar_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('avatar_url') } }

        field :billing_address, Models::Shared::Address, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('billing_address') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # Timestamp for when the customer was soft deleted.
        field :deleted_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('deleted_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The email address of the customer. This must be unique within the organization.
        field :email, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }
        # Whether the customer email address is verified. The address is automatically verified when the customer accesses the customer portal using their email address.
        field :email_verified, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email_verified') } }
        # The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
        field :external_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_id') } }
        # The ID of the customer.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

        field :metadata, T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The name of the customer.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # The ID of the organization owning the customer.
        field :organization_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

        field :tax_id, T::Array[T.any(::String, Models::Shared::TaxIDFormat)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tax_id') } }


        sig { params(avatar_url: ::String, billing_address: Models::Shared::Address, created_at: ::DateTime, deleted_at: ::DateTime, email: ::String, email_verified: T::Boolean, external_id: ::String, id: ::String, metadata: T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], modified_at: ::DateTime, name: ::String, organization_id: ::String, tax_id: T::Array[T.any(::String, Models::Shared::TaxIDFormat)]).void }
        def initialize(avatar_url: nil, billing_address: nil, created_at: nil, deleted_at: nil, email: nil, email_verified: nil, external_id: nil, id: nil, metadata: nil, modified_at: nil, name: nil, organization_id: nil, tax_id: nil)
          @avatar_url = avatar_url
          @billing_address = billing_address
          @created_at = created_at
          @deleted_at = deleted_at
          @email = email
          @email_verified = email_verified
          @external_id = external_id
          @id = id
          @metadata = metadata
          @modified_at = modified_at
          @name = name
          @organization_id = organization_id
          @tax_id = tax_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @avatar_url == other.avatar_url
          return false unless @billing_address == other.billing_address
          return false unless @created_at == other.created_at
          return false unless @deleted_at == other.deleted_at
          return false unless @email == other.email
          return false unless @email_verified == other.email_verified
          return false unless @external_id == other.external_id
          return false unless @id == other.id
          return false unless @metadata == other.metadata
          return false unless @modified_at == other.modified_at
          return false unless @name == other.name
          return false unless @organization_id == other.organization_id
          return false unless @tax_id == other.tax_id
          true
        end
      end
    end
  end
end
