# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class LicenseKeyValidate
        extend T::Sig
        include Crystalline::MetadataFields


        field :key, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('key') } }

        field :organization_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

        field :activation_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('activation_id') } }

        field :benefit_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('benefit_id') } }
        # Key-value object allowing you to set conditions that must match when validating the license key.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :conditions, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('conditions') } }

        field :customer_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_id') } }

        field :increment_usage, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('increment_usage') } }


        sig { params(key: ::String, organization_id: ::String, activation_id: T.nilable(::String), benefit_id: T.nilable(::String), conditions: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), customer_id: T.nilable(::String), increment_usage: T.nilable(::Integer)).void }
        def initialize(key: nil, organization_id: nil, activation_id: nil, benefit_id: nil, conditions: nil, customer_id: nil, increment_usage: nil)
          @key = key
          @organization_id = organization_id
          @activation_id = activation_id
          @benefit_id = benefit_id
          @conditions = conditions
          @customer_id = customer_id
          @increment_usage = increment_usage
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @key == other.key
          return false unless @organization_id == other.organization_id
          return false unless @activation_id == other.activation_id
          return false unless @benefit_id == other.benefit_id
          return false unless @conditions == other.conditions
          return false unless @customer_id == other.customer_id
          return false unless @increment_usage == other.increment_usage
          true
        end
      end
    end
  end
end
