# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class LicenseKeyDeactivate
        extend T::Sig
        include Crystalline::MetadataFields


        field :activation_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('activation_id') } }

        field :key, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('key') } }

        field :organization_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }


        sig { params(activation_id: ::String, key: ::String, organization_id: ::String).void }
        def initialize(activation_id: nil, key: nil, organization_id: nil)
          @activation_id = activation_id
          @key = key
          @organization_id = organization_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @activation_id == other.activation_id
          return false unless @key == other.key
          return false unless @organization_id == other.organization_id
          true
        end
      end
    end
  end
end
