# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # The aggregation to apply on the filtered events to calculate the meter.
      class MeterCreateAggregation
        extend T::Sig
        include Crystalline::MetadataFields



        
        def initialize; end

        def ==(other)
          return false unless other.is_a? self.class
          true
        end
      end
    end
  end
end
