# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class MeterUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        # The aggregation to apply on the filtered events to calculate the meter.
        field :aggregation, T.nilable(T.any(Models::Shared::CountAggregation, Models::Shared::PropertyAggregation)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('aggregation') }, 'discriminator': 'func' }
        # The filter to apply on events that'll be used to calculate the meter.
        field :filter, T.nilable(Models::Shared::Filter), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('filter') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # The name of the meter. Will be shown on customer's invoices and usage.
        field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }


        sig { params(aggregation: T.nilable(T.any(Models::Shared::CountAggregation, Models::Shared::PropertyAggregation)), filter: T.nilable(Models::Shared::Filter), metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), name: T.nilable(::String)).void }
        def initialize(aggregation: nil, filter: nil, metadata: nil, name: nil)
          @aggregation = aggregation
          @filter = filter
          @metadata = metadata
          @name = name
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @aggregation == other.aggregation
          return false unless @filter == other.filter
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          true
        end
      end
    end
  end
end
