# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class MeterQuantities
        extend T::Sig
        include Crystalline::MetadataFields


        field :quantities, T::Array[Models::Shared::MeterQuantity], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('quantities') } }
        # The total quantity for the period.
        field :total, ::Float, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('total') } }


        sig { params(quantities: T::Array[Models::Shared::MeterQuantity], total: ::Float).void }
        def initialize(quantities: nil, total: nil)
          @quantities = quantities
          @total = total
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @quantities == other.quantities
          return false unless @total == other.total
          true
        end
      end
    end
  end
end
