# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class MetricPeriod
        extend T::Sig
        include Crystalline::MetadataFields


        field :active_subscriptions, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('active_subscriptions') } }

        field :average_order_value, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('average_order_value') } }

        field :cumulative_revenue, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cumulative_revenue') } }

        field :monthly_recurring_revenue, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('monthly_recurring_revenue') } }

        field :new_subscriptions, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('new_subscriptions') } }

        field :new_subscriptions_revenue, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('new_subscriptions_revenue') } }

        field :one_time_products, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('one_time_products') } }

        field :one_time_products_revenue, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('one_time_products_revenue') } }

        field :orders, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('orders') } }

        field :renewed_subscriptions, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('renewed_subscriptions') } }

        field :renewed_subscriptions_revenue, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('renewed_subscriptions_revenue') } }

        field :revenue, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('revenue') } }
        # Timestamp of this period data.
        field :timestamp, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('timestamp'), 'decoder': Utils.datetime_from_iso_format(false) } }


        sig { params(active_subscriptions: ::Integer, average_order_value: ::Integer, cumulative_revenue: ::Integer, monthly_recurring_revenue: ::Integer, new_subscriptions: ::Integer, new_subscriptions_revenue: ::Integer, one_time_products: ::Integer, one_time_products_revenue: ::Integer, orders: ::Integer, renewed_subscriptions: ::Integer, renewed_subscriptions_revenue: ::Integer, revenue: ::Integer, timestamp: ::DateTime).void }
        def initialize(active_subscriptions: nil, average_order_value: nil, cumulative_revenue: nil, monthly_recurring_revenue: nil, new_subscriptions: nil, new_subscriptions_revenue: nil, one_time_products: nil, one_time_products_revenue: nil, orders: nil, renewed_subscriptions: nil, renewed_subscriptions_revenue: nil, revenue: nil, timestamp: nil)
          @active_subscriptions = active_subscriptions
          @average_order_value = average_order_value
          @cumulative_revenue = cumulative_revenue
          @monthly_recurring_revenue = monthly_recurring_revenue
          @new_subscriptions = new_subscriptions
          @new_subscriptions_revenue = new_subscriptions_revenue
          @one_time_products = one_time_products
          @one_time_products_revenue = one_time_products_revenue
          @orders = orders
          @renewed_subscriptions = renewed_subscriptions
          @renewed_subscriptions_revenue = renewed_subscriptions_revenue
          @revenue = revenue
          @timestamp = timestamp
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @active_subscriptions == other.active_subscriptions
          return false unless @average_order_value == other.average_order_value
          return false unless @cumulative_revenue == other.cumulative_revenue
          return false unless @monthly_recurring_revenue == other.monthly_recurring_revenue
          return false unless @new_subscriptions == other.new_subscriptions
          return false unless @new_subscriptions_revenue == other.new_subscriptions_revenue
          return false unless @one_time_products == other.one_time_products
          return false unless @one_time_products_revenue == other.one_time_products_revenue
          return false unless @orders == other.orders
          return false unless @renewed_subscriptions == other.renewed_subscriptions
          return false unless @renewed_subscriptions_revenue == other.renewed_subscriptions_revenue
          return false unless @revenue == other.revenue
          return false unless @timestamp == other.timestamp
          true
        end
      end
    end
  end
end
