# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Information about a metric.
      class Metric
        extend T::Sig
        include Crystalline::MetadataFields

        # Human-readable name for the metric.
        field :display_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('display_name') } }
        # Unique identifier for the metric.
        field :slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('slug') } }

        field :type, Models::Shared::MetricType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), 'decoder': Utils.enum_from_string(Models::Shared::MetricType, false) } }


        sig { params(display_name: ::String, slug: ::String, type: Models::Shared::MetricType).void }
        def initialize(display_name: nil, slug: nil, type: nil)
          @display_name = display_name
          @slug = slug
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @display_name == other.display_name
          return false unless @slug == other.slug
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
