# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Date limits to get metrics.
      class MetricsLimits
        extend T::Sig
        include Crystalline::MetadataFields

        # Date interval limits to get metrics for each interval.
        field :intervals, Models::Shared::MetricsIntervalsLimits, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('intervals') } }
        # Minimum date to get metrics.
        field :min_date, ::Date, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('min_date'), 'decoder': Utils.date_from_iso_format(false) } }


        sig { params(intervals: Models::Shared::MetricsIntervalsLimits, min_date: ::Date).void }
        def initialize(intervals: nil, min_date: nil)
          @intervals = intervals
          @min_date = min_date
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @intervals == other.intervals
          return false unless @min_date == other.min_date
          true
        end
      end
    end
  end
end
