# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OAuth2ClientConfigurationUpdate
        extend T::Sig
        include Crystalline::MetadataFields


        field :client_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client_id') } }

        field :client_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client_name') } }

        field :redirect_uris, T::Array[::String], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('redirect_uris') } }

        field :client_uri, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client_uri') } }

        field :grant_types, T.nilable(T::Array[Models::Shared::OAuth2ClientConfigurationUpdateGrantTypes]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('grant_types') } }

        field :logo_uri, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('logo_uri') } }

        field :policy_uri, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('policy_uri') } }

        field :response_types, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('response_types') } }

        field :scope, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('scope') } }

        field :token_endpoint_auth_method, T.nilable(Models::Shared::OAuth2ClientConfigurationUpdateTokenEndpointAuthMethod), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('token_endpoint_auth_method'), 'decoder': Utils.enum_from_string(Models::Shared::OAuth2ClientConfigurationUpdateTokenEndpointAuthMethod, true) } }

        field :tos_uri, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tos_uri') } }


        sig { params(client_id: ::String, client_name: ::String, redirect_uris: T::Array[::String], client_uri: T.nilable(::String), grant_types: T.nilable(T::Array[Models::Shared::OAuth2ClientConfigurationUpdateGrantTypes]), logo_uri: T.nilable(::String), policy_uri: T.nilable(::String), response_types: T.nilable(T::Array[::String]), scope: T.nilable(::String), token_endpoint_auth_method: T.nilable(Models::Shared::OAuth2ClientConfigurationUpdateTokenEndpointAuthMethod), tos_uri: T.nilable(::String)).void }
        def initialize(client_id: nil, client_name: nil, redirect_uris: nil, client_uri: nil, grant_types: nil, logo_uri: nil, policy_uri: nil, response_types: nil, scope: nil, token_endpoint_auth_method: nil, tos_uri: nil)
          @client_id = client_id
          @client_name = client_name
          @redirect_uris = redirect_uris
          @client_uri = client_uri
          @grant_types = grant_types
          @logo_uri = logo_uri
          @policy_uri = policy_uri
          @response_types = response_types
          @scope = scope
          @token_endpoint_auth_method = token_endpoint_auth_method
          @tos_uri = tos_uri
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @client_id == other.client_id
          return false unless @client_name == other.client_name
          return false unless @redirect_uris == other.redirect_uris
          return false unless @client_uri == other.client_uri
          return false unless @grant_types == other.grant_types
          return false unless @logo_uri == other.logo_uri
          return false unless @policy_uri == other.policy_uri
          return false unless @response_types == other.response_types
          return false unless @scope == other.scope
          return false unless @token_endpoint_auth_method == other.token_endpoint_auth_method
          return false unless @tos_uri == other.tos_uri
          true
        end
      end
    end
  end
end
