# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OAuth2ClientConfigurationUpdateTokenEndpointAuthMethod < T::Enum
        enums do
          CLIENT_SECRET_BASIC = new('client_secret_basic')
          CLIENT_SECRET_POST = new('client_secret_post')
          NONE = new('none')
        end
      end
    end
  end
end
