# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OAuth2ClientPublic
        extend T::Sig
        include Crystalline::MetadataFields


        field :client_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client_id') } }

        field :client_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client_name') } }

        field :client_uri, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('client_uri') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :logo_uri, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('logo_uri') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :policy_uri, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('policy_uri') } }

        field :tos_uri, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tos_uri') } }


        sig { params(client_id: ::String, client_name: ::String, client_uri: ::String, created_at: ::DateTime, logo_uri: ::String, modified_at: ::DateTime, policy_uri: ::String, tos_uri: ::String).void }
        def initialize(client_id: nil, client_name: nil, client_uri: nil, created_at: nil, logo_uri: nil, modified_at: nil, policy_uri: nil, tos_uri: nil)
          @client_id = client_id
          @client_name = client_name
          @client_uri = client_uri
          @created_at = created_at
          @logo_uri = logo_uri
          @modified_at = modified_at
          @policy_uri = policy_uri
          @tos_uri = tos_uri
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @client_id == other.client_id
          return false unless @client_name == other.client_name
          return false unless @client_uri == other.client_uri
          return false unless @created_at == other.created_at
          return false unless @logo_uri == other.logo_uri
          return false unless @modified_at == other.modified_at
          return false unless @policy_uri == other.policy_uri
          return false unless @tos_uri == other.tos_uri
          true
        end
      end
    end
  end
end
