# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OAuth2ClientConfigurationGrantTypes < T::Enum
        enums do
          AUTHORIZATION_CODE = new('authorization_code')
          REFRESH_TOKEN = new('refresh_token')
        end
      end
    end
  end
end
