# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Order
        extend T::Sig
        include Crystalline::MetadataFields

        # Amount in cents, after discounts but before taxes.
        # 
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount') } }

        field :billing_address, Models::Shared::Address, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('billing_address') } }

        field :billing_reason, Models::Shared::OrderBillingReason, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('billing_reason'), 'decoder': Utils.enum_from_string(Models::Shared::OrderBillingReason, false) } }

        field :checkout_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('checkout_id') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }

        field :currency, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('currency') } }

        field :customer, Models::Shared::OrderCustomer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer') } }

        field :customer_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_id') } }

        field :discount, T.any(Models::Shared::DiscountFixedOnceForeverDurationBase, Models::Shared::DiscountFixedRepeatDurationBase, Models::Shared::DiscountPercentageOnceForeverDurationBase, Models::Shared::DiscountPercentageRepeatDurationBase), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount') } }
        # Discount amount in cents.
        field :discount_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount_amount') } }

        field :discount_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount_id') } }
        # The ID of the object.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Line items composing the order.
        field :items, T::Array[Models::Shared::OrderItemSchema], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('items') } }

        field :metadata, T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # Amount in cents, after discounts but before taxes.
        field :net_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('net_amount') } }
        # Whether the order has been paid for.
        field :paid, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('paid') } }

        field :product, Models::Shared::OrderProduct, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product') } }

        field :product_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_id') } }
        # Amount refunded in cents.
        field :refunded_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('refunded_amount') } }
        # Sales tax refunded in cents.
        field :refunded_tax_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('refunded_tax_amount') } }

        field :status, Models::Shared::OrderStatus, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Shared::OrderStatus, false) } }

        field :subscription, Models::Shared::OrderSubscription, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subscription') } }

        field :subscription_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subscription_id') } }
        # Amount in cents, before discounts and taxes.
        field :subtotal_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subtotal_amount') } }
        # Sales tax amount in cents.
        field :tax_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tax_amount') } }
        # Amount in cents, after discounts and taxes.
        field :total_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('total_amount') } }
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :user_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }
        # Key-value object storing custom field values.
        field :custom_field_data, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, T::Boolean, ::DateTime)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('custom_field_data') } }


        sig { params(amount: ::Integer, billing_address: Models::Shared::Address, billing_reason: Models::Shared::OrderBillingReason, checkout_id: ::String, created_at: ::DateTime, currency: ::String, customer: Models::Shared::OrderCustomer, customer_id: ::String, discount: T.any(Models::Shared::DiscountFixedOnceForeverDurationBase, Models::Shared::DiscountFixedRepeatDurationBase, Models::Shared::DiscountPercentageOnceForeverDurationBase, Models::Shared::DiscountPercentageRepeatDurationBase), discount_amount: ::Integer, discount_id: ::String, id: ::String, items: T::Array[Models::Shared::OrderItemSchema], metadata: T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)], modified_at: ::DateTime, net_amount: ::Integer, paid: T::Boolean, product: Models::Shared::OrderProduct, product_id: ::String, refunded_amount: ::Integer, refunded_tax_amount: ::Integer, status: Models::Shared::OrderStatus, subscription: Models::Shared::OrderSubscription, subscription_id: ::String, subtotal_amount: ::Integer, tax_amount: ::Integer, total_amount: ::Integer, user_id: ::String, custom_field_data: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, T::Boolean, ::DateTime)])).void }
        def initialize(amount: nil, billing_address: nil, billing_reason: nil, checkout_id: nil, created_at: nil, currency: nil, customer: nil, customer_id: nil, discount: nil, discount_amount: nil, discount_id: nil, id: nil, items: nil, metadata: nil, modified_at: nil, net_amount: nil, paid: nil, product: nil, product_id: nil, refunded_amount: nil, refunded_tax_amount: nil, status: nil, subscription: nil, subscription_id: nil, subtotal_amount: nil, tax_amount: nil, total_amount: nil, user_id: nil, custom_field_data: nil)
          @amount = amount
          @billing_address = billing_address
          @billing_reason = billing_reason
          @checkout_id = checkout_id
          @created_at = created_at
          @currency = currency
          @customer = customer
          @customer_id = customer_id
          @discount = discount
          @discount_amount = discount_amount
          @discount_id = discount_id
          @id = id
          @items = items
          @metadata = metadata
          @modified_at = modified_at
          @net_amount = net_amount
          @paid = paid
          @product = product
          @product_id = product_id
          @refunded_amount = refunded_amount
          @refunded_tax_amount = refunded_tax_amount
          @status = status
          @subscription = subscription
          @subscription_id = subscription_id
          @subtotal_amount = subtotal_amount
          @tax_amount = tax_amount
          @total_amount = total_amount
          @user_id = user_id
          @custom_field_data = custom_field_data
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @billing_address == other.billing_address
          return false unless @billing_reason == other.billing_reason
          return false unless @checkout_id == other.checkout_id
          return false unless @created_at == other.created_at
          return false unless @currency == other.currency
          return false unless @customer == other.customer
          return false unless @customer_id == other.customer_id
          return false unless @discount == other.discount
          return false unless @discount_amount == other.discount_amount
          return false unless @discount_id == other.discount_id
          return false unless @id == other.id
          return false unless @items == other.items
          return false unless @metadata == other.metadata
          return false unless @modified_at == other.modified_at
          return false unless @net_amount == other.net_amount
          return false unless @paid == other.paid
          return false unless @product == other.product
          return false unless @product_id == other.product_id
          return false unless @refunded_amount == other.refunded_amount
          return false unless @refunded_tax_amount == other.refunded_tax_amount
          return false unless @status == other.status
          return false unless @subscription == other.subscription
          return false unless @subscription_id == other.subscription_id
          return false unless @subtotal_amount == other.subtotal_amount
          return false unless @tax_amount == other.tax_amount
          return false unless @total_amount == other.total_amount
          return false unless @user_id == other.user_id
          return false unless @custom_field_data == other.custom_field_data
          true
        end
      end
    end
  end
end
