# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OrderSortProperty < T::Enum
        enums do
          CREATED_AT = new('created_at')
          MINUS_CREATED_AT = new('-created_at')
          AMOUNT = new('amount')
          MINUS_AMOUNT = new('-amount')
          NET_AMOUNT = new('net_amount')
          MINUS_NET_AMOUNT = new('-net_amount')
          CUSTOMER = new('customer')
          MINUS_CUSTOMER = new('-customer')
          PRODUCT = new('product')
          MINUS_PRODUCT = new('-product')
          DISCOUNT = new('discount')
          MINUS_DISCOUNT = new('-discount')
          SUBSCRIPTION = new('subscription')
          MINUS_SUBSCRIPTION = new('-subscription')
        end
      end
    end
  end
end
