# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OrderBillingReason < T::Enum
        enums do
          PURCHASE = new('purchase')
          SUBSCRIPTION_CREATE = new('subscription_create')
          SUBSCRIPTION_CYCLE = new('subscription_cycle')
          SUBSCRIPTION_UPDATE = new('subscription_update')
        end
      end
    end
  end
end
