# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Organization
        extend T::Sig
        include Crystalline::MetadataFields

        # Avatar URL shown in checkout, customer portal, emails etc.
        field :avatar_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('avatar_url') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # When the business details were submitted.
        field :details_submitted_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('details_submitted_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # Public support email.
        field :email, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }
        # Organization feature settings
        field :feature_settings, Models::Shared::OrganizationFeatureSettings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('feature_settings') } }
        # The organization ID.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # Organization name shown in checkout, customer portal, emails etc.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # Unique organization slug in checkout, customer portal and credit card statements.
        field :slug, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('slug') } }
        # Links to social profiles.
        field :socials, T::Array[Models::Shared::OrganizationSocialLink], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('socials') } }

        field :subscription_settings, Models::Shared::OrganizationSubscriptionSettings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subscription_settings') } }
        # Official website of the organization.
        field :website, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('website') } }


        sig { params(avatar_url: ::String, created_at: ::DateTime, details_submitted_at: ::DateTime, email: ::String, feature_settings: Models::Shared::OrganizationFeatureSettings, id: ::String, modified_at: ::DateTime, name: ::String, slug: ::String, socials: T::Array[Models::Shared::OrganizationSocialLink], subscription_settings: Models::Shared::OrganizationSubscriptionSettings, website: ::String).void }
        def initialize(avatar_url: nil, created_at: nil, details_submitted_at: nil, email: nil, feature_settings: nil, id: nil, modified_at: nil, name: nil, slug: nil, socials: nil, subscription_settings: nil, website: nil)
          @avatar_url = avatar_url
          @created_at = created_at
          @details_submitted_at = details_submitted_at
          @email = email
          @feature_settings = feature_settings
          @id = id
          @modified_at = modified_at
          @name = name
          @slug = slug
          @socials = socials
          @subscription_settings = subscription_settings
          @website = website
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @avatar_url == other.avatar_url
          return false unless @created_at == other.created_at
          return false unless @details_submitted_at == other.details_submitted_at
          return false unless @email == other.email
          return false unless @feature_settings == other.feature_settings
          return false unless @id == other.id
          return false unless @modified_at == other.modified_at
          return false unless @name == other.name
          return false unless @slug == other.slug
          return false unless @socials == other.socials
          return false unless @subscription_settings == other.subscription_settings
          return false unless @website == other.website
          true
        end
      end
    end
  end
end
