# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class OrganizationUpdate
        extend T::Sig
        include Crystalline::MetadataFields


        field :avatar_url, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('avatar_url') } }
        # Additional, private, business details Polar needs about active organizations for compliance (KYC).
        field :details, T.nilable(Models::Shared::OrganizationDetails), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('details') } }
        # Public support email.
        field :email, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }

        field :feature_settings, T.nilable(Models::Shared::OrganizationFeatureSettings), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('feature_settings') } }

        field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # Links to social profiles.
        field :socials, T.nilable(T::Array[Models::Shared::OrganizationSocialLink]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('socials') } }

        field :subscription_settings, T.nilable(Models::Shared::OrganizationSubscriptionSettings), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subscription_settings') } }
        # Official website of the organization.
        field :website, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('website') } }


        sig { params(avatar_url: T.nilable(::String), details: T.nilable(Models::Shared::OrganizationDetails), email: T.nilable(::String), feature_settings: T.nilable(Models::Shared::OrganizationFeatureSettings), name: T.nilable(::String), socials: T.nilable(T::Array[Models::Shared::OrganizationSocialLink]), subscription_settings: T.nilable(Models::Shared::OrganizationSubscriptionSettings), website: T.nilable(::String)).void }
        def initialize(avatar_url: nil, details: nil, email: nil, feature_settings: nil, name: nil, socials: nil, subscription_settings: nil, website: nil)
          @avatar_url = avatar_url
          @details = details
          @email = email
          @feature_settings = feature_settings
          @name = name
          @socials = socials
          @subscription_settings = subscription_settings
          @website = website
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @avatar_url == other.avatar_url
          return false unless @details == other.details
          return false unless @email == other.email
          return false unless @feature_settings == other.feature_settings
          return false unless @name == other.name
          return false unless @socials == other.socials
          return false unless @subscription_settings == other.subscription_settings
          return false unless @website == other.website
          true
        end
      end
    end
  end
end
