# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema to create a file to be used as an organization avatar.
      class OrganizationAvatarFileCreate
        extend T::Sig
        include Crystalline::MetadataFields

        # MIME type of the file. Only images are supported for this type of file.
        field :mime_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('mime_type') } }

        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

        field :service, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('service') } }
        # Size of the file. A maximum of 1 MB is allowed for this type of file.
        field :size, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('size') } }

        field :upload, Models::Shared::S3FileCreateMultipart, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('upload') } }

        field :checksum_sha256_base64, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('checksum_sha256_base64') } }

        field :organization_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }

        field :version, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('version') } }


        sig { params(mime_type: ::String, name: ::String, service: ::String, size: ::Integer, upload: Models::Shared::S3FileCreateMultipart, checksum_sha256_base64: T.nilable(::String), organization_id: T.nilable(::String), version: T.nilable(::String)).void }
        def initialize(mime_type: nil, name: nil, service: nil, size: nil, upload: nil, checksum_sha256_base64: nil, organization_id: nil, version: nil)
          @mime_type = mime_type
          @name = name
          @service = service
          @size = size
          @upload = upload
          @checksum_sha256_base64 = checksum_sha256_base64
          @organization_id = organization_id
          @version = version
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @mime_type == other.mime_type
          return false unless @name == other.name
          return false unless @service == other.service
          return false unless @size == other.size
          return false unless @upload == other.upload
          return false unless @checksum_sha256_base64 == other.checksum_sha256_base64
          return false unless @organization_id == other.organization_id
          return false unless @version == other.version
          true
        end
      end
    end
  end
end
