# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Pagination
        extend T::Sig
        include Crystalline::MetadataFields


        field :max_page, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('max_page') } }

        field :total_count, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('total_count') } }


        sig { params(max_page: ::Integer, total_count: ::Integer).void }
        def initialize(max_page: nil, total_count: nil)
          @max_page = max_page
          @total_count = total_count
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @max_page == other.max_page
          return false unless @total_count == other.total_count
          true
        end
      end
    end
  end
end
