# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class PaymentMethodCardData
        extend T::Sig
        include Crystalline::MetadataFields


        field :brand, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('brand') } }

        field :exp_month, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('exp_month') } }

        field :exp_year, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('exp_year') } }

        field :last4, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('last4') } }

        field :wallet, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('wallet') } }


        sig { params(brand: ::String, exp_month: ::Integer, exp_year: ::Integer, last4: ::String, wallet: T.nilable(::String)).void }
        def initialize(brand: nil, exp_month: nil, exp_year: nil, last4: nil, wallet: nil)
          @brand = brand
          @exp_month = exp_month
          @exp_year = exp_year
          @last4 = last4
          @wallet = wallet
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @brand == other.brand
          return false unless @exp_month == other.exp_month
          return false unless @exp_year == other.exp_year
          return false unless @last4 == other.last4
          return false unless @wallet == other.wallet
          true
        end
      end
    end
  end
end
