# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class PaymentProcessor < T::Enum
        enums do
          STRIPE = new('stripe')
        end
      end
    end
  end
end
