# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Permission - The permission level to grant. Read more about roles and their permissions on [GitHub documentation](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role).
      class Permission < T::Enum
        enums do
          PULL = new('pull')
          TRIAGE = new('triage')
          PUSH = new('push')
          MAINTAIN = new('maintain')
          ADMIN = new('admin')
        end
      end
    end
  end
end
