# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # A metered, usage-based, price for a product, with a fixed unit price.
      class ProductPriceMeteredUnit
        extend T::Sig
        include Crystalline::MetadataFields


        field :amount_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount_type') } }
        # The maximum amount in cents that can be charged, regardless of the number of units consumed.
        field :cap_amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cap_amount') } }
        # Creation timestamp of the object.
        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The ID of the price.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
        # Whether the price is archived and no longer available.
        field :is_archived, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('is_archived') } }
        # A meter associated to a metered price.
        field :meter, Models::Shared::ProductPriceMeter, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('meter') } }
        # The ID of the meter associated to the price.
        field :meter_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('meter_id') } }
        # Last modification timestamp of the object.
        field :modified_at, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(false) } }
        # The currency.
        field :price_currency, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('price_currency') } }
        # The ID of the product owning the price.
        field :product_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_id') } }
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :recurring_interval, Models::Shared::SubscriptionRecurringInterval, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('recurring_interval'), 'decoder': Utils.enum_from_string(Models::Shared::SubscriptionRecurringInterval, false) } }

        field :type, Models::Shared::ProductPriceType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), 'decoder': Utils.enum_from_string(Models::Shared::ProductPriceType, false) } }
        # The price per unit in cents.
        field :unit_amount, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('unit_amount') } }


        sig { params(amount_type: ::String, cap_amount: ::Integer, created_at: ::DateTime, id: ::String, is_archived: T::Boolean, meter: Models::Shared::ProductPriceMeter, meter_id: ::String, modified_at: ::DateTime, price_currency: ::String, product_id: ::String, recurring_interval: Models::Shared::SubscriptionRecurringInterval, type: Models::Shared::ProductPriceType, unit_amount: ::String).void }
        def initialize(amount_type: nil, cap_amount: nil, created_at: nil, id: nil, is_archived: nil, meter: nil, meter_id: nil, modified_at: nil, price_currency: nil, product_id: nil, recurring_interval: nil, type: nil, unit_amount: nil)
          @amount_type = amount_type
          @cap_amount = cap_amount
          @created_at = created_at
          @id = id
          @is_archived = is_archived
          @meter = meter
          @meter_id = meter_id
          @modified_at = modified_at
          @price_currency = price_currency
          @product_id = product_id
          @recurring_interval = recurring_interval
          @type = type
          @unit_amount = unit_amount
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount_type == other.amount_type
          return false unless @cap_amount == other.cap_amount
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @is_archived == other.is_archived
          return false unless @meter == other.meter
          return false unless @meter_id == other.meter_id
          return false unless @modified_at == other.modified_at
          return false unless @price_currency == other.price_currency
          return false unless @product_id == other.product_id
          return false unless @recurring_interval == other.recurring_interval
          return false unless @type == other.type
          return false unless @unit_amount == other.unit_amount
          true
        end
      end
    end
  end
end
