# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Schema to create a product.
      class ProductCreate
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the product.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # List of available prices for this product. It should contain at most one static price (fixed, custom or free), and any number of metered prices. Metered prices are not supported on one-time purchase products.
        field :prices, T::Array[T.any(Models::Shared::ProductPriceFixedCreate, Models::Shared::ProductPriceCustomCreate, Models::Shared::ProductPriceFreeCreate, Models::Shared::ProductPriceMeteredUnitCreate)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('prices') } }
        # The recurring interval of the product. If `None`, the product is a one-time purchase.
        field :recurring_interval, Models::Shared::SubscriptionRecurringInterval, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('recurring_interval'), 'decoder': Utils.enum_from_string(Models::Shared::SubscriptionRecurringInterval, false) } }
        # List of custom fields to attach.
        field :attached_custom_fields, T.nilable(T::Array[Models::Shared::AttachedCustomFieldCreate]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('attached_custom_fields') } }
        # The description of the product.
        field :description, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }
        # List of file IDs. Each one must be on the same organization as the product, of type `product_media` and correctly uploaded.
        field :medias, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('medias') } }
        # Key-value object allowing you to store additional information.
        # 
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        # 
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        # 
        # You can store up to **50 key-value pairs**.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }
        # The ID of the organization owning the product. **Required unless you use an organization token.**
        field :organization_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id') } }


        sig { params(name: ::String, prices: T::Array[T.any(Models::Shared::ProductPriceFixedCreate, Models::Shared::ProductPriceCustomCreate, Models::Shared::ProductPriceFreeCreate, Models::Shared::ProductPriceMeteredUnitCreate)], recurring_interval: Models::Shared::SubscriptionRecurringInterval, attached_custom_fields: T.nilable(T::Array[Models::Shared::AttachedCustomFieldCreate]), description: T.nilable(::String), medias: T.nilable(T::Array[::String]), metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]), organization_id: T.nilable(::String)).void }
        def initialize(name: nil, prices: nil, recurring_interval: nil, attached_custom_fields: nil, description: nil, medias: nil, metadata: nil, organization_id: nil)
          @name = name
          @prices = prices
          @recurring_interval = recurring_interval
          @attached_custom_fields = attached_custom_fields
          @description = description
          @medias = medias
          @metadata = metadata
          @organization_id = organization_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @prices == other.prices
          return false unless @recurring_interval == other.recurring_interval
          return false unless @attached_custom_fields == other.attached_custom_fields
          return false unless @description == other.description
          return false unless @medias == other.medias
          return false unless @metadata == other.metadata
          return false unless @organization_id == other.organization_id
          true
        end
      end
    end
  end
end
