# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class ProductPriceType < T::Enum
        enums do
          ONE_TIME = new('one_time')
          RECURRING = new('recurring')
        end
      end
    end
  end
end
