# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class RefundStatus < T::Enum
        enums do
          PENDING = new('pending')
          SUCCEEDED = new('succeeded')
          FAILED = new('failed')
          CANCELED = new('canceled')
        end
      end
    end
  end
end
