# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class S3FileCreateMultipart
        extend T::Sig
        include Crystalline::MetadataFields


        field :parts, T::Array[Models::Shared::S3FileCreatePart], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('parts') } }


        sig { params(parts: T::Array[Models::Shared::S3FileCreatePart]).void }
        def initialize(parts: nil)
          @parts = parts
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @parts == other.parts
          true
        end
      end
    end
  end
end
