# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class SubscriptionProrationBehavior < T::Enum
        enums do
          INVOICE = new('invoice')
          PRORATE = new('prorate')
        end
      end
    end
  end
end
