# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class SubscriptionCancel
        extend T::Sig
        include Crystalline::MetadataFields

        # Cancel an active subscription once the current period ends.
        # 
        # Or uncancel a subscription currently set to be revoked at period end.
        field :cancel_at_period_end, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('cancel_at_period_end') } }
        # Customer feedback and why they decided to cancel.
        # 
        # **IMPORTANT:**
        # Do not use this to store internal notes! It's intended to be input
        # from the customer and is therefore also available in their Polar
        # purchases library.
        # 
        # Only set this in case your own service is requesting the reason from the
        # customer. Or you copy a message directly from a customer
        # conversation, i.e support.
        field :customer_cancellation_comment, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_cancellation_comment') } }
        # Customer reason for cancellation.
        # 
        # Helpful to monitor reasons behind churn for future improvements.
        # 
        # Only set this in case your own service is requesting the reason from the
        # customer. Or you know based on direct conversations, i.e support, with
        # the customer.
        # 
        # * `too_expensive`: Too expensive for the customer.
        # * `missing_features`: Customer is missing certain features.
        # * `switched_service`: Customer switched to another service.
        # * `unused`: Customer is not using it enough.
        # * `customer_service`: Customer is not satisfied with the customer service.
        # * `low_quality`: Customer is unhappy with the quality.
        # * `too_complex`: Customer considers the service too complicated.
        # * `other`: Other reason(s).
        field :customer_cancellation_reason, T.nilable(Models::Shared::CustomerCancellationReason), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_cancellation_reason'), 'decoder': Utils.enum_from_string(Models::Shared::CustomerCancellationReason, true) } }


        sig { params(cancel_at_period_end: T::Boolean, customer_cancellation_comment: T.nilable(::String), customer_cancellation_reason: T.nilable(Models::Shared::CustomerCancellationReason)).void }
        def initialize(cancel_at_period_end: nil, customer_cancellation_comment: nil, customer_cancellation_reason: nil)
          @cancel_at_period_end = cancel_at_period_end
          @customer_cancellation_comment = customer_cancellation_comment
          @customer_cancellation_reason = customer_cancellation_reason
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @cancel_at_period_end == other.cancel_at_period_end
          return false unless @customer_cancellation_comment == other.customer_cancellation_comment
          return false unless @customer_cancellation_reason == other.customer_cancellation_reason
          true
        end
      end
    end
  end
end
