# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # TaxIDFormat - List of supported tax ID formats.
      # 
      # Ref: https://docs.stripe.com/billing/customer/tax-ids#supported-tax-id
      class TaxIDFormat < T::Enum
        enums do
          AD_NRT = new('ad_nrt')
          AE_TRN = new('ae_trn')
          AR_CUIT = new('ar_cuit')
          AU_ABN = new('au_abn')
          AU_ARN = new('au_arn')
          BG_UIC = new('bg_uic')
          BH_VAT = new('bh_vat')
          BO_TIN = new('bo_tin')
          BR_CNPJ = new('br_cnpj')
          BR_CPF = new('br_cpf')
          CA_BN = new('ca_bn')
          CA_GST_HST = new('ca_gst_hst')
          CA_PST_BC = new('ca_pst_bc')
          CA_PST_MB = new('ca_pst_mb')
          CA_PST_SK = new('ca_pst_sk')
          CA_QST = new('ca_qst')
          CH_UID = new('ch_uid')
          CH_VAT = new('ch_vat')
          CL_TIN = new('cl_tin')
          CN_TIN = new('cn_tin')
          CO_NIT = new('co_nit')
          CR_TIN = new('cr_tin')
          DE_STN = new('de_stn')
          DO_RCN = new('do_rcn')
          EC_RUC = new('ec_ruc')
          EG_TIN = new('eg_tin')
          ES_CIF = new('es_cif')
          EU_OSS_VAT = new('eu_oss_vat')
          EU_VAT = new('eu_vat')
          GB_VAT = new('gb_vat')
          GE_VAT = new('ge_vat')
          HK_BR = new('hk_br')
          HR_OIB = new('hr_oib')
          HU_TIN = new('hu_tin')
          ID_NPWP = new('id_npwp')
          IL_VAT = new('il_vat')
          IN_GST = new('in_gst')
          IS_VAT = new('is_vat')
          JP_CN = new('jp_cn')
          JP_RN = new('jp_rn')
          JP_TRN = new('jp_trn')
          KE_PIN = new('ke_pin')
          KR_BRN = new('kr_brn')
          KZ_BIN = new('kz_bin')
          LI_UID = new('li_uid')
          MX_RFC = new('mx_rfc')
          MY_FRP = new('my_frp')
          MY_ITN = new('my_itn')
          MY_SST = new('my_sst')
          NG_TIN = new('ng_tin')
          NO_VAT = new('no_vat')
          NO_VOEC = new('no_voec')
          NZ_GST = new('nz_gst')
          OM_VAT = new('om_vat')
          PE_RUC = new('pe_ruc')
          PH_TIN = new('ph_tin')
          RO_TIN = new('ro_tin')
          RS_PIB = new('rs_pib')
          RU_INN = new('ru_inn')
          RU_KPP = new('ru_kpp')
          SA_VAT = new('sa_vat')
          SG_GST = new('sg_gst')
          SG_UEN = new('sg_uen')
          SI_TIN = new('si_tin')
          SV_NIT = new('sv_nit')
          TH_VAT = new('th_vat')
          TR_TIN = new('tr_tin')
          TW_VAT = new('tw_vat')
          UA_VAT = new('ua_vat')
          US_EIN = new('us_ein')
          UY_RUC = new('uy_ruc')
          VE_RIF = new('ve_rif')
          VN_TIN = new('vn_tin')
          ZA_VAT = new('za_vat')
        end
      end
    end
  end
end
