# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Timeframe < T::Enum
        enums do
          YEAR = new('year')
          MONTH = new('month')
          DAY = new('day')
        end
      end
    end
  end
end
