# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class TokenResponse
        extend T::Sig
        include Crystalline::MetadataFields


        field :access_token, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('access_token') } }

        field :expires_in, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('expires_in') } }

        field :id_token, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_token') } }

        field :refresh_token, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('refresh_token') } }

        field :scope, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('scope') } }

        field :token_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('token_type') } }


        sig { params(access_token: ::String, expires_in: ::Integer, id_token: ::String, refresh_token: ::String, scope: ::String, token_type: ::String).void }
        def initialize(access_token: nil, expires_in: nil, id_token: nil, refresh_token: nil, scope: nil, token_type: nil)
          @access_token = access_token
          @expires_in = expires_in
          @id_token = id_token
          @refresh_token = refresh_token
          @scope = scope
          @token_type = token_type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @access_token == other.access_token
          return false unless @expires_in == other.expires_in
          return false unless @id_token == other.id_token
          return false unless @refresh_token == other.refresh_token
          return false unless @scope == other.scope
          return false unless @token_type == other.token_type
          true
        end
      end
    end
  end
end
