# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class UserInfoUser
        extend T::Sig
        include Crystalline::MetadataFields


        field :sub, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sub') } }

        field :email, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }

        field :email_verified, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email_verified') } }

        field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }


        sig { params(sub: ::String, email: T.nilable(::String), email_verified: T.nilable(T::Boolean), name: T.nilable(::String)).void }
        def initialize(sub: nil, email: nil, email_verified: nil, name: nil)
          @sub = sub
          @email = email
          @email_verified = email_verified
          @name = name
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @sub == other.sub
          return false unless @email == other.email
          return false unless @email_verified == other.email_verified
          return false unless @name == other.name
          true
        end
      end
    end
  end
end
