# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class ValidationError
        extend T::Sig
        include Crystalline::MetadataFields


        field :loc, T::Array[T.any(::String, ::Integer)], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('loc') } }

        field :msg, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('msg') } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


        sig { params(loc: T::Array[T.any(::String, ::Integer)], msg: ::String, type: ::String).void }
        def initialize(loc: nil, msg: nil, type: nil)
          @loc = loc
          @msg = msg
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @loc == other.loc
          return false unless @msg == other.msg
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
