# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Sent when a new subscription is created.
      # 
      # When this event occurs, the subscription `status` might not be `active` yet, as we can still have to wait for the first payment to be processed.
      # 
      # **Discord & Slack support:** Full
      class WebhookSubscriptionCreatedPayload
        extend T::Sig
        include Crystalline::MetadataFields


        field :data, Models::Shared::Subscription, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data') } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


        sig { params(data: Models::Shared::Subscription, type: ::String).void }
        def initialize(data: nil, type: nil)
          @data = data
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @data == other.data
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
