# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Sent when a customer is updated.
      # 
      # This event is fired when the customer details are updated.
      # 
      # If you want to be notified when a customer subscription or benefit state changes, you should listen to the `customer_state_changed` event.
      # 
      # **Discord & Slack support:** Basic
      class WebhookCustomerUpdatedPayload
        extend T::Sig
        include Crystalline::MetadataFields

        # A customer in an organization.
        field :data, Models::Shared::Customer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data') } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


        sig { params(data: Models::Shared::Customer, type: ::String).void }
        def initialize(data: nil, type: nil)
          @data = data
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @data == other.data
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
