# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Sent when a new benefit is created.
      # 
      # **Discord & Slack support:** Basic
      class WebhookBenefitCreatedPayload
        extend T::Sig
        include Crystalline::MetadataFields


        field :data, T.any(Models::Shared::BenefitCustom, Models::Shared::BenefitDiscord, Models::Shared::BenefitGitHubRepository, Models::Shared::BenefitDownloadables, Models::Shared::BenefitLicenseKeys, Models::Shared::BenefitMeterCredit), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data') } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


        sig { params(data: T.any(Models::Shared::BenefitCustom, Models::Shared::BenefitDiscord, Models::Shared::BenefitGitHubRepository, Models::Shared::BenefitDownloadables, Models::Shared::BenefitLicenseKeys, Models::Shared::BenefitMeterCredit), type: ::String).void }
        def initialize(data: nil, type: nil)
          @data = data
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @data == other.data
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
