# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    
      # Sent when a new order is created.
      # 
      # A new order is created when:
      # 
      # * A customer purchases a one-time product. In this case, `billing_reason` is set to `purchase`.
      # * A customer starts a subscription. In this case, `billing_reason` is set to `subscription_create`.
      # * A subscription is renewed. In this case, `billing_reason` is set to `subscription_cycle`.
      # * A subscription is upgraded or downgraded with an immediate proration invoice. In this case, `billing_reason` is set to `subscription_update`.
      # 
      # <Warning>The order might not be paid yet, so the `status` field might be `pending`.</Warning>
      # 
      # **Discord & Slack support:** Full
      class WebhookOrderCreatedPayload
        extend T::Sig
        include Crystalline::MetadataFields


        field :data, Models::Shared::Order, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data') } }

        field :type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


        sig { params(data: Models::Shared::Order, type: ::String).void }
        def initialize(data: nil, type: nil)
          @data = data
          @type = type
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @data == other.data
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
