# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class BenefitsGrantsRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
        # Filter by customer.
        field :customer_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'customer_id', 'style': 'form', 'explode': true } }
        # Filter by granted status. If `true`, only granted benefits will be returned. If `false`, only revoked benefits will be returned. 
        field :is_granted, T.nilable(T::Boolean), { 'query_param': { 'field_name': 'is_granted', 'style': 'form', 'explode': true } }
        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }


        sig { params(id: ::String, customer_id: T.nilable(T.any(::String, T::Array[::String])), is_granted: T.nilable(T::Boolean), limit: T.nilable(::Integer), page: T.nilable(::Integer)).void }
        def initialize(id: nil, customer_id: nil, is_granted: nil, limit: nil, page: nil)
          @id = id
          @customer_id = customer_id
          @is_granted = is_granted
          @limit = limit
          @page = page
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @customer_id == other.customer_id
          return false unless @is_granted == other.is_granted
          return false unless @limit == other.limit
          return false unless @page == other.page
          true
        end
      end
    end
  end
end
