# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class BenefitsUpdateRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

        field :request_body, T.any(Models::Shared::BenefitCustomUpdate, Models::Shared::BenefitDiscordUpdate, Models::Shared::BenefitGitHubRepositoryUpdate, Models::Shared::BenefitDownloadablesUpdate, Models::Shared::BenefitLicenseKeysUpdate, Models::Shared::BenefitMeterCreditUpdate), { 'request': { 'media_type': 'application/json' } }


        sig { params(id: ::String, request_body: T.any(Models::Shared::BenefitCustomUpdate, Models::Shared::BenefitDiscordUpdate, Models::Shared::BenefitGitHubRepositoryUpdate, Models::Shared::BenefitDownloadablesUpdate, Models::Shared::BenefitLicenseKeysUpdate, Models::Shared::BenefitMeterCreditUpdate)).void }
        def initialize(id: nil, request_body: nil)
          @id = id
          @request_body = request_body
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
