# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class BenefitsListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # Filter by description.
        field :query, T.nilable(::String), { 'query_param': { 'field_name': 'query', 'style': 'form', 'explode': true } }
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field :sorting, T.nilable(T::Array[Models::Shared::BenefitSortProperty]), { 'query_param': { 'field_name': 'sorting', 'style': 'form', 'explode': true } }
        # Filter by benefit type.
        field :type_filter, T.nilable(T.any(Models::Shared::BenefitType, T::Array[Models::Shared::BenefitType])), { 'query_param': { 'field_name': 'type', 'style': 'form', 'explode': true } }


        sig { params(limit: T.nilable(::Integer), organization_id: T.nilable(T.any(::String, T::Array[::String])), page: T.nilable(::Integer), query: T.nilable(::String), sorting: T.nilable(T::Array[Models::Shared::BenefitSortProperty]), type_filter: T.nilable(T.any(Models::Shared::BenefitType, T::Array[Models::Shared::BenefitType]))).void }
        def initialize(limit: nil, organization_id: nil, page: nil, query: nil, sorting: nil, type_filter: nil)
          @limit = limit
          @organization_id = organization_id
          @page = page
          @query = query
          @sorting = sorting
          @type_filter = type_filter
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @limit == other.limit
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          return false unless @query == other.query
          return false unless @sorting == other.sorting
          return false unless @type_filter == other.type_filter
          true
        end
      end
    end
  end
end
