# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CheckoutLinksListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # Filter by product ID.
        field :product_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'product_id', 'style': 'form', 'explode': true } }
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field :sorting, T.nilable(T::Array[Models::Shared::CheckoutLinkSortProperty]), { 'query_param': { 'field_name': 'sorting', 'style': 'form', 'explode': true } }


        sig { params(limit: T.nilable(::Integer), organization_id: T.nilable(T.any(::String, T::Array[::String])), page: T.nilable(::Integer), product_id: T.nilable(T.any(::String, T::Array[::String])), sorting: T.nilable(T::Array[Models::Shared::CheckoutLinkSortProperty])).void }
        def initialize(limit: nil, organization_id: nil, page: nil, product_id: nil, sorting: nil)
          @limit = limit
          @organization_id = organization_id
          @page = page
          @product_id = product_id
          @sorting = sorting
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @limit == other.limit
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          return false unless @product_id == other.product_id
          return false unless @sorting == other.sorting
          true
        end
      end
    end
  end
end
