# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CustomerPortalCustomersGetSecurity
        extend T::Sig
        include Crystalline::MetadataFields


        field :customer_session, ::String, { 'security': { 'scheme': true, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' } }


        sig { params(customer_session: ::String).void }
        def initialize(customer_session: nil)
          @customer_session = customer_session
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @customer_session == other.customer_session
          true
        end
      end
    end
  end
end
