# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CustomerPortalLicenseKeysListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by a specific benefit
        field :benefit_id, T.nilable(::String), { 'query_param': { 'field_name': 'benefit_id', 'style': 'form', 'explode': true } }
        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }


        sig { params(benefit_id: T.nilable(::String), limit: T.nilable(::Integer), organization_id: T.nilable(T.any(::String, T::Array[::String])), page: T.nilable(::Integer)).void }
        def initialize(benefit_id: nil, limit: nil, organization_id: nil, page: nil)
          @benefit_id = benefit_id
          @limit = limit
          @organization_id = organization_id
          @page = page
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefit_id == other.benefit_id
          return false unless @limit == other.limit
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          true
        end
      end
    end
  end
end
