# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CustomerPortalDownloadablesCustomerPortalDownloadablesGetRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :token, ::String, { 'path_param': { 'field_name': 'token', 'style': 'simple', 'explode': false } }


        sig { params(token: ::String).void }
        def initialize(token: nil)
          @token = token
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @token == other.token
          true
        end
      end
    end
  end
end
