# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CustomersGetRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The customer ID.
        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }


        sig { params(id: ::String).void }
        def initialize(id: nil)
          @id = id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          true
        end
      end
    end
  end
end
