# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CustomerPortalBenefitGrantsListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by benefit ID.
        field :benefit_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'benefit_id', 'style': 'form', 'explode': true } }
        # Filter by checkout ID.
        field :checkout_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'checkout_id', 'style': 'form', 'explode': true } }
        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Filter by order ID.
        field :order_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'order_id', 'style': 'form', 'explode': true } }
        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field :sorting, T.nilable(T::Array[Models::Shared::CustomerBenefitGrantSortProperty]), { 'query_param': { 'field_name': 'sorting', 'style': 'form', 'explode': true } }
        # Filter by subscription ID.
        field :subscription_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'subscription_id', 'style': 'form', 'explode': true } }
        # Filter by benefit type.
        field :type_filter, T.nilable(T.any(Models::Shared::BenefitType, T::Array[Models::Shared::BenefitType])), { 'query_param': { 'field_name': 'type', 'style': 'form', 'explode': true } }


        sig { params(benefit_id: T.nilable(T.any(::String, T::Array[::String])), checkout_id: T.nilable(T.any(::String, T::Array[::String])), limit: T.nilable(::Integer), order_id: T.nilable(T.any(::String, T::Array[::String])), organization_id: T.nilable(T.any(::String, T::Array[::String])), page: T.nilable(::Integer), sorting: T.nilable(T::Array[Models::Shared::CustomerBenefitGrantSortProperty]), subscription_id: T.nilable(T.any(::String, T::Array[::String])), type_filter: T.nilable(T.any(Models::Shared::BenefitType, T::Array[Models::Shared::BenefitType]))).void }
        def initialize(benefit_id: nil, checkout_id: nil, limit: nil, order_id: nil, organization_id: nil, page: nil, sorting: nil, subscription_id: nil, type_filter: nil)
          @benefit_id = benefit_id
          @checkout_id = checkout_id
          @limit = limit
          @order_id = order_id
          @organization_id = organization_id
          @page = page
          @sorting = sorting
          @subscription_id = subscription_id
          @type_filter = type_filter
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefit_id == other.benefit_id
          return false unless @checkout_id == other.checkout_id
          return false unless @limit == other.limit
          return false unless @order_id == other.order_id
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          return false unless @sorting == other.sorting
          return false unless @subscription_id == other.subscription_id
          return false unless @type_filter == other.type_filter
          true
        end
      end
    end
  end
end
