# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CustomersListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by exact email.
        field :email, T.nilable(::String), { 'query_param': { 'field_name': 'email', 'style': 'form', 'explode': true } }
        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
        field :metadata, T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, T::Boolean, T::Array[::String], T::Array[::Integer], T::Array[T::Boolean])]), { 'query_param': { 'field_name': 'metadata', 'style': 'deepObject', 'explode': true } }
        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # Filter by name or email.
        field :query, T.nilable(::String), { 'query_param': { 'field_name': 'query', 'style': 'form', 'explode': true } }
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field :sorting, T.nilable(T::Array[Models::Shared::CustomerSortProperty]), { 'query_param': { 'field_name': 'sorting', 'style': 'form', 'explode': true } }


        sig { params(email: T.nilable(::String), limit: T.nilable(::Integer), metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, T::Boolean, T::Array[::String], T::Array[::Integer], T::Array[T::Boolean])]), organization_id: T.nilable(T.any(::String, T::Array[::String])), page: T.nilable(::Integer), query: T.nilable(::String), sorting: T.nilable(T::Array[Models::Shared::CustomerSortProperty])).void }
        def initialize(email: nil, limit: nil, metadata: nil, organization_id: nil, page: nil, query: nil, sorting: nil)
          @email = email
          @limit = limit
          @metadata = metadata
          @organization_id = organization_id
          @page = page
          @query = query
          @sorting = sorting
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @email == other.email
          return false unless @limit == other.limit
          return false unless @metadata == other.metadata
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          return false unless @query == other.query
          return false unless @sorting == other.sorting
          true
        end
      end
    end
  end
end
