# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class EventsListNamesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by customer ID.
        field :customer_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'customer_id', 'style': 'form', 'explode': true } }
        # Filter by external customer ID.
        field :external_customer_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'external_customer_id', 'style': 'form', 'explode': true } }
        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # Query to filter event names.
        field :query, T.nilable(::String), { 'query_param': { 'field_name': 'query', 'style': 'form', 'explode': true } }
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field :sorting, T.nilable(T::Array[Models::Shared::EventNamesSortProperty]), { 'query_param': { 'field_name': 'sorting', 'style': 'form', 'explode': true } }
        # Filter by event source.
        field :source, T.nilable(T.any(Models::Shared::EventSource, T::Array[Models::Shared::EventSource])), { 'query_param': { 'field_name': 'source', 'style': 'form', 'explode': true } }


        sig { params(customer_id: T.nilable(T.any(::String, T::Array[::String])), external_customer_id: T.nilable(T.any(::String, T::Array[::String])), limit: T.nilable(::Integer), organization_id: T.nilable(T.any(::String, T::Array[::String])), page: T.nilable(::Integer), query: T.nilable(::String), sorting: T.nilable(T::Array[Models::Shared::EventNamesSortProperty]), source: T.nilable(T.any(Models::Shared::EventSource, T::Array[Models::Shared::EventSource]))).void }
        def initialize(customer_id: nil, external_customer_id: nil, limit: nil, organization_id: nil, page: nil, query: nil, sorting: nil, source: nil)
          @customer_id = customer_id
          @external_customer_id = external_customer_id
          @limit = limit
          @organization_id = organization_id
          @page = page
          @query = query
          @sorting = sorting
          @source = source
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @customer_id == other.customer_id
          return false unless @external_customer_id == other.external_customer_id
          return false unless @limit == other.limit
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          return false unless @query == other.query
          return false unless @sorting == other.sorting
          return false unless @source == other.source
          true
        end
      end
    end
  end
end
