# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class FilesUploadedRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :file_upload_completed, Models::Shared::FileUploadCompleted, { 'request': { 'media_type': 'application/json' } }
        # The file ID.
        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }


        sig { params(file_upload_completed: Models::Shared::FileUploadCompleted, id: ::String).void }
        def initialize(file_upload_completed: nil, id: nil)
          @file_upload_completed = file_upload_completed
          @id = id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @file_upload_completed == other.file_upload_completed
          return false unless @id == other.id
          true
        end
      end
    end
  end
end
