# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class FilesUpdateRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :file_patch, Models::Shared::FilePatch, { 'request': { 'media_type': 'application/json' } }
        # The file ID.
        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }


        sig { params(file_patch: Models::Shared::FilePatch, id: ::String).void }
        def initialize(file_patch: nil, id: nil)
          @file_patch = file_patch
          @id = id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @file_patch == other.file_patch
          return false unless @id == other.id
          true
        end
      end
    end
  end
end
