# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class LicenseKeysUpdateRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

        field :license_key_update, Models::Shared::LicenseKeyUpdate, { 'request': { 'media_type': 'application/json' } }


        sig { params(id: ::String, license_key_update: Models::Shared::LicenseKeyUpdate).void }
        def initialize(id: nil, license_key_update: nil)
          @id = id
          @license_key_update = license_key_update
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @license_key_update == other.license_key_update
          true
        end
      end
    end
  end
end
