# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class Oauth2ClientsOauth2UpdateClientRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :client_id, ::String, { 'path_param': { 'field_name': 'client_id', 'style': 'simple', 'explode': false } }

        field :o_auth2_client_configuration_update, Models::Shared::OAuth2ClientConfigurationUpdate, { 'request': { 'media_type': 'application/json' } }


        sig { params(client_id: ::String, o_auth2_client_configuration_update: Models::Shared::OAuth2ClientConfigurationUpdate).void }
        def initialize(client_id: nil, o_auth2_client_configuration_update: nil)
          @client_id = client_id
          @o_auth2_client_configuration_update = o_auth2_client_configuration_update
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @client_id == other.client_id
          return false unless @o_auth2_client_configuration_update == other.o_auth2_client_configuration_update
          true
        end
      end
    end
  end
end
