# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class Oauth2ClientsOauth2GetClientRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :client_id, ::String, { 'path_param': { 'field_name': 'client_id', 'style': 'simple', 'explode': false } }


        sig { params(client_id: ::String).void }
        def initialize(client_id: nil)
          @client_id = client_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @client_id == other.client_id
          true
        end
      end
    end
  end
end
