# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class ProductsListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter products granting specific benefit.
        field :benefit_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'benefit_id', 'style': 'form', 'explode': true } }
        # Filter by product ID.
        field :id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'id', 'style': 'form', 'explode': true } }
        # Filter on archived products.
        field :is_archived, T.nilable(T::Boolean), { 'query_param': { 'field_name': 'is_archived', 'style': 'form', 'explode': true } }
        # Filter on recurring products. If `true`, only subscriptions tiers are returned. If `false`, only one-time purchase products are returned. 
        field :is_recurring, T.nilable(T::Boolean), { 'query_param': { 'field_name': 'is_recurring', 'style': 'form', 'explode': true } }
        # Size of a page, defaults to 10. Maximum is 100.
        field :limit, T.nilable(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Page number, defaults to 1.
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # Filter by product name.
        field :query, T.nilable(::String), { 'query_param': { 'field_name': 'query', 'style': 'form', 'explode': true } }
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field :sorting, T.nilable(T::Array[Models::Shared::ProductSortProperty]), { 'query_param': { 'field_name': 'sorting', 'style': 'form', 'explode': true } }


        sig { params(benefit_id: T.nilable(T.any(::String, T::Array[::String])), id: T.nilable(T.any(::String, T::Array[::String])), is_archived: T.nilable(T::Boolean), is_recurring: T.nilable(T::Boolean), limit: T.nilable(::Integer), organization_id: T.nilable(T.any(::String, T::Array[::String])), page: T.nilable(::Integer), query: T.nilable(::String), sorting: T.nilable(T::Array[Models::Shared::ProductSortProperty])).void }
        def initialize(benefit_id: nil, id: nil, is_archived: nil, is_recurring: nil, limit: nil, organization_id: nil, page: nil, query: nil, sorting: nil)
          @benefit_id = benefit_id
          @id = id
          @is_archived = is_archived
          @is_recurring = is_recurring
          @limit = limit
          @organization_id = organization_id
          @page = page
          @query = query
          @sorting = sorting
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefit_id == other.benefit_id
          return false unless @id == other.id
          return false unless @is_archived == other.is_archived
          return false unless @is_recurring == other.is_recurring
          return false unless @limit == other.limit
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          return false unless @query == other.query
          return false unless @sorting == other.sorting
          true
        end
      end
    end
  end
end
