# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class SubscriptionsUpdateRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The subscription ID.
        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

        field :subscription_update, T.any(Models::Shared::SubscriptionUpdateProduct, Models::Shared::SubscriptionCancel, Models::Shared::SubscriptionRevoke), { 'request': { 'media_type': 'application/json' } }


        sig { params(id: ::String, subscription_update: T.any(Models::Shared::SubscriptionUpdateProduct, Models::Shared::SubscriptionCancel, Models::Shared::SubscriptionRevoke)).void }
        def initialize(id: nil, subscription_update: nil)
          @id = id
          @subscription_update = subscription_update
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @subscription_update == other.subscription_update
          true
        end
      end
    end
  end
end
