# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class SubscriptionsExportRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by organization ID.
        field :organization_id, T.nilable(T.any(::String, T::Array[::String])), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }


        sig { params(organization_id: T.nilable(T.any(::String, T::Array[::String]))).void }
        def initialize(organization_id: nil)
          @organization_id = organization_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @organization_id == other.organization_id
          true
        end
      end
    end
  end
end
